// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basemgrlogin.proto

#ifndef PROTOBUF_basemgrlogin_2eproto__INCLUDED
#define PROTOBUF_basemgrlogin_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace basemgrlogin {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_basemgrlogin_2eproto();
void protobuf_AssignDesc_basemgrlogin_2eproto();
void protobuf_ShutdownFile_basemgrlogin_2eproto();

class PendingAccount_Request;
class PendingAccountEx_Request;
class LoginAccountBaseappAddr_Return;
class BaseappInitProgress;

// ===================================================================

class PendingAccount_Request : public ::google::protobuf::Message {
 public:
  PendingAccount_Request();
  virtual ~PendingAccount_Request();

  PendingAccount_Request(const PendingAccount_Request& from);

  inline PendingAccount_Request& operator=(const PendingAccount_Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PendingAccount_Request& default_instance();

  void Swap(PendingAccount_Request* other);

  // implements Message ----------------------------------------------

  PendingAccount_Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PendingAccount_Request& from);
  void MergeFrom(const PendingAccount_Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string loginName = 1;
  inline bool has_loginname() const;
  inline void clear_loginname();
  static const int kLoginNameFieldNumber = 1;
  inline const ::std::string& loginname() const;
  inline void set_loginname(const ::std::string& value);
  inline void set_loginname(const char* value);
  inline void set_loginname(const char* value, size_t size);
  inline ::std::string* mutable_loginname();
  inline ::std::string* release_loginname();
  inline void set_allocated_loginname(::std::string* loginname);

  // optional string accountName = 2;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 2;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  inline void set_allocated_accountname(::std::string* accountname);

  // optional string password = 3;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 3;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // optional uint64 dbid = 4;
  inline bool has_dbid() const;
  inline void clear_dbid();
  static const int kDbidFieldNumber = 4;
  inline ::google::protobuf::uint64 dbid() const;
  inline void set_dbid(::google::protobuf::uint64 value);

  // optional uint32 flags = 5;
  inline bool has_flags() const;
  inline void clear_flags();
  static const int kFlagsFieldNumber = 5;
  inline ::google::protobuf::uint32 flags() const;
  inline void set_flags(::google::protobuf::uint32 value);

  // optional string extraData = 6;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 6;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:basemgrlogin.PendingAccount_Request)
 private:
  inline void set_has_loginname();
  inline void clear_has_loginname();
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_password();
  inline void clear_has_password();
  inline void set_has_dbid();
  inline void clear_has_dbid();
  inline void set_has_flags();
  inline void clear_has_flags();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* loginname_;
  ::std::string* accountname_;
  ::std::string* password_;
  ::google::protobuf::uint64 dbid_;
  ::std::string* extradata_;
  ::google::protobuf::uint32 flags_;
  friend void  protobuf_AddDesc_basemgrlogin_2eproto();
  friend void protobuf_AssignDesc_basemgrlogin_2eproto();
  friend void protobuf_ShutdownFile_basemgrlogin_2eproto();

  void InitAsDefaultInstance();
  static PendingAccount_Request* default_instance_;
};
// -------------------------------------------------------------------

class PendingAccountEx_Request : public ::google::protobuf::Message {
 public:
  PendingAccountEx_Request();
  virtual ~PendingAccountEx_Request();

  PendingAccountEx_Request(const PendingAccountEx_Request& from);

  inline PendingAccountEx_Request& operator=(const PendingAccountEx_Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PendingAccountEx_Request& default_instance();

  void Swap(PendingAccountEx_Request* other);

  // implements Message ----------------------------------------------

  PendingAccountEx_Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PendingAccountEx_Request& from);
  void MergeFrom(const PendingAccountEx_Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 componentID = 1;
  inline bool has_componentid() const;
  inline void clear_componentid();
  static const int kComponentIDFieldNumber = 1;
  inline ::google::protobuf::uint64 componentid() const;
  inline void set_componentid(::google::protobuf::uint64 value);

  // optional string loginName = 2;
  inline bool has_loginname() const;
  inline void clear_loginname();
  static const int kLoginNameFieldNumber = 2;
  inline const ::std::string& loginname() const;
  inline void set_loginname(const ::std::string& value);
  inline void set_loginname(const char* value);
  inline void set_loginname(const char* value, size_t size);
  inline ::std::string* mutable_loginname();
  inline ::std::string* release_loginname();
  inline void set_allocated_loginname(::std::string* loginname);

  // optional string accountName = 3;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 3;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  inline void set_allocated_accountname(::std::string* accountname);

  // optional string password = 4;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 4;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // optional int32 entityID = 5;
  inline bool has_entityid() const;
  inline void clear_entityid();
  static const int kEntityIDFieldNumber = 5;
  inline ::google::protobuf::int32 entityid() const;
  inline void set_entityid(::google::protobuf::int32 value);

  // optional uint64 dbid = 6;
  inline bool has_dbid() const;
  inline void clear_dbid();
  static const int kDbidFieldNumber = 6;
  inline ::google::protobuf::uint64 dbid() const;
  inline void set_dbid(::google::protobuf::uint64 value);

  // optional uint32 flags = 7;
  inline bool has_flags() const;
  inline void clear_flags();
  static const int kFlagsFieldNumber = 7;
  inline ::google::protobuf::uint32 flags() const;
  inline void set_flags(::google::protobuf::uint32 value);

  // optional string extraData = 8;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 8;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:basemgrlogin.PendingAccountEx_Request)
 private:
  inline void set_has_componentid();
  inline void clear_has_componentid();
  inline void set_has_loginname();
  inline void clear_has_loginname();
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_password();
  inline void clear_has_password();
  inline void set_has_entityid();
  inline void clear_has_entityid();
  inline void set_has_dbid();
  inline void clear_has_dbid();
  inline void set_has_flags();
  inline void clear_has_flags();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 componentid_;
  ::std::string* loginname_;
  ::std::string* accountname_;
  ::std::string* password_;
  ::google::protobuf::uint64 dbid_;
  ::google::protobuf::int32 entityid_;
  ::google::protobuf::uint32 flags_;
  ::std::string* extradata_;
  friend void  protobuf_AddDesc_basemgrlogin_2eproto();
  friend void protobuf_AssignDesc_basemgrlogin_2eproto();
  friend void protobuf_ShutdownFile_basemgrlogin_2eproto();

  void InitAsDefaultInstance();
  static PendingAccountEx_Request* default_instance_;
};
// -------------------------------------------------------------------

class LoginAccountBaseappAddr_Return : public ::google::protobuf::Message {
 public:
  LoginAccountBaseappAddr_Return();
  virtual ~LoginAccountBaseappAddr_Return();

  LoginAccountBaseappAddr_Return(const LoginAccountBaseappAddr_Return& from);

  inline LoginAccountBaseappAddr_Return& operator=(const LoginAccountBaseappAddr_Return& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginAccountBaseappAddr_Return& default_instance();

  void Swap(LoginAccountBaseappAddr_Return* other);

  // implements Message ----------------------------------------------

  LoginAccountBaseappAddr_Return* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginAccountBaseappAddr_Return& from);
  void MergeFrom(const LoginAccountBaseappAddr_Return& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string loginName = 1;
  inline bool has_loginname() const;
  inline void clear_loginname();
  static const int kLoginNameFieldNumber = 1;
  inline const ::std::string& loginname() const;
  inline void set_loginname(const ::std::string& value);
  inline void set_loginname(const char* value);
  inline void set_loginname(const char* value, size_t size);
  inline ::std::string* mutable_loginname();
  inline ::std::string* release_loginname();
  inline void set_allocated_loginname(::std::string* loginname);

  // optional string accountName = 2;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 2;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  inline void set_allocated_accountname(::std::string* accountname);

  // optional string ip = 3;
  inline bool has_ip() const;
  inline void clear_ip();
  static const int kIpFieldNumber = 3;
  inline const ::std::string& ip() const;
  inline void set_ip(const ::std::string& value);
  inline void set_ip(const char* value);
  inline void set_ip(const char* value, size_t size);
  inline ::std::string* mutable_ip();
  inline ::std::string* release_ip();
  inline void set_allocated_ip(::std::string* ip);

  // optional uint32 port = 4;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 4;
  inline ::google::protobuf::uint32 port() const;
  inline void set_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:basemgrlogin.LoginAccountBaseappAddr_Return)
 private:
  inline void set_has_loginname();
  inline void clear_has_loginname();
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_ip();
  inline void clear_has_ip();
  inline void set_has_port();
  inline void clear_has_port();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* loginname_;
  ::std::string* accountname_;
  ::std::string* ip_;
  ::google::protobuf::uint32 port_;
  friend void  protobuf_AddDesc_basemgrlogin_2eproto();
  friend void protobuf_AssignDesc_basemgrlogin_2eproto();
  friend void protobuf_ShutdownFile_basemgrlogin_2eproto();

  void InitAsDefaultInstance();
  static LoginAccountBaseappAddr_Return* default_instance_;
};
// -------------------------------------------------------------------

class BaseappInitProgress : public ::google::protobuf::Message {
 public:
  BaseappInitProgress();
  virtual ~BaseappInitProgress();

  BaseappInitProgress(const BaseappInitProgress& from);

  inline BaseappInitProgress& operator=(const BaseappInitProgress& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BaseappInitProgress& default_instance();

  void Swap(BaseappInitProgress* other);

  // implements Message ----------------------------------------------

  BaseappInitProgress* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BaseappInitProgress& from);
  void MergeFrom(const BaseappInitProgress& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 baseappsInitProgress = 1;
  inline bool has_baseappsinitprogress() const;
  inline void clear_baseappsinitprogress();
  static const int kBaseappsInitProgressFieldNumber = 1;
  inline ::google::protobuf::uint32 baseappsinitprogress() const;
  inline void set_baseappsinitprogress(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:basemgrlogin.BaseappInitProgress)
 private:
  inline void set_has_baseappsinitprogress();
  inline void clear_has_baseappsinitprogress();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 baseappsinitprogress_;
  friend void  protobuf_AddDesc_basemgrlogin_2eproto();
  friend void protobuf_AssignDesc_basemgrlogin_2eproto();
  friend void protobuf_ShutdownFile_basemgrlogin_2eproto();

  void InitAsDefaultInstance();
  static BaseappInitProgress* default_instance_;
};
// ===================================================================


// ===================================================================

// PendingAccount_Request

// optional string loginName = 1;
inline bool PendingAccount_Request::has_loginname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PendingAccount_Request::set_has_loginname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PendingAccount_Request::clear_has_loginname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PendingAccount_Request::clear_loginname() {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_->clear();
  }
  clear_has_loginname();
}
inline const ::std::string& PendingAccount_Request::loginname() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccount_Request.loginName)
  return *loginname_;
}
inline void PendingAccount_Request::set_loginname(const ::std::string& value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccount_Request.loginName)
}
inline void PendingAccount_Request::set_loginname(const char* value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.PendingAccount_Request.loginName)
}
inline void PendingAccount_Request::set_loginname(const char* value, size_t size) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.PendingAccount_Request.loginName)
}
inline ::std::string* PendingAccount_Request::mutable_loginname() {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.PendingAccount_Request.loginName)
  return loginname_;
}
inline ::std::string* PendingAccount_Request::release_loginname() {
  clear_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = loginname_;
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PendingAccount_Request::set_allocated_loginname(::std::string* loginname) {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete loginname_;
  }
  if (loginname) {
    set_has_loginname();
    loginname_ = loginname;
  } else {
    clear_has_loginname();
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.PendingAccount_Request.loginName)
}

// optional string accountName = 2;
inline bool PendingAccount_Request::has_accountname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PendingAccount_Request::set_has_accountname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PendingAccount_Request::clear_has_accountname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PendingAccount_Request::clear_accountname() {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_->clear();
  }
  clear_has_accountname();
}
inline const ::std::string& PendingAccount_Request::accountname() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccount_Request.accountName)
  return *accountname_;
}
inline void PendingAccount_Request::set_accountname(const ::std::string& value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccount_Request.accountName)
}
inline void PendingAccount_Request::set_accountname(const char* value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.PendingAccount_Request.accountName)
}
inline void PendingAccount_Request::set_accountname(const char* value, size_t size) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.PendingAccount_Request.accountName)
}
inline ::std::string* PendingAccount_Request::mutable_accountname() {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.PendingAccount_Request.accountName)
  return accountname_;
}
inline ::std::string* PendingAccount_Request::release_accountname() {
  clear_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = accountname_;
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PendingAccount_Request::set_allocated_accountname(::std::string* accountname) {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete accountname_;
  }
  if (accountname) {
    set_has_accountname();
    accountname_ = accountname;
  } else {
    clear_has_accountname();
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.PendingAccount_Request.accountName)
}

// optional string password = 3;
inline bool PendingAccount_Request::has_password() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PendingAccount_Request::set_has_password() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PendingAccount_Request::clear_has_password() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PendingAccount_Request::clear_password() {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& PendingAccount_Request::password() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccount_Request.password)
  return *password_;
}
inline void PendingAccount_Request::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccount_Request.password)
}
inline void PendingAccount_Request::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.PendingAccount_Request.password)
}
inline void PendingAccount_Request::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.PendingAccount_Request.password)
}
inline ::std::string* PendingAccount_Request::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.PendingAccount_Request.password)
  return password_;
}
inline ::std::string* PendingAccount_Request::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PendingAccount_Request::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.PendingAccount_Request.password)
}

// optional uint64 dbid = 4;
inline bool PendingAccount_Request::has_dbid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PendingAccount_Request::set_has_dbid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PendingAccount_Request::clear_has_dbid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PendingAccount_Request::clear_dbid() {
  dbid_ = GOOGLE_ULONGLONG(0);
  clear_has_dbid();
}
inline ::google::protobuf::uint64 PendingAccount_Request::dbid() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccount_Request.dbid)
  return dbid_;
}
inline void PendingAccount_Request::set_dbid(::google::protobuf::uint64 value) {
  set_has_dbid();
  dbid_ = value;
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccount_Request.dbid)
}

// optional uint32 flags = 5;
inline bool PendingAccount_Request::has_flags() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PendingAccount_Request::set_has_flags() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PendingAccount_Request::clear_has_flags() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PendingAccount_Request::clear_flags() {
  flags_ = 0u;
  clear_has_flags();
}
inline ::google::protobuf::uint32 PendingAccount_Request::flags() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccount_Request.flags)
  return flags_;
}
inline void PendingAccount_Request::set_flags(::google::protobuf::uint32 value) {
  set_has_flags();
  flags_ = value;
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccount_Request.flags)
}

// optional string extraData = 6;
inline bool PendingAccount_Request::has_extradata() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PendingAccount_Request::set_has_extradata() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PendingAccount_Request::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PendingAccount_Request::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& PendingAccount_Request::extradata() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccount_Request.extraData)
  return *extradata_;
}
inline void PendingAccount_Request::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccount_Request.extraData)
}
inline void PendingAccount_Request::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.PendingAccount_Request.extraData)
}
inline void PendingAccount_Request::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.PendingAccount_Request.extraData)
}
inline ::std::string* PendingAccount_Request::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.PendingAccount_Request.extraData)
  return extradata_;
}
inline ::std::string* PendingAccount_Request::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PendingAccount_Request::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.PendingAccount_Request.extraData)
}

// -------------------------------------------------------------------

// PendingAccountEx_Request

// optional uint64 componentID = 1;
inline bool PendingAccountEx_Request::has_componentid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PendingAccountEx_Request::set_has_componentid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PendingAccountEx_Request::clear_has_componentid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PendingAccountEx_Request::clear_componentid() {
  componentid_ = GOOGLE_ULONGLONG(0);
  clear_has_componentid();
}
inline ::google::protobuf::uint64 PendingAccountEx_Request::componentid() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccountEx_Request.componentID)
  return componentid_;
}
inline void PendingAccountEx_Request::set_componentid(::google::protobuf::uint64 value) {
  set_has_componentid();
  componentid_ = value;
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccountEx_Request.componentID)
}

// optional string loginName = 2;
inline bool PendingAccountEx_Request::has_loginname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PendingAccountEx_Request::set_has_loginname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PendingAccountEx_Request::clear_has_loginname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PendingAccountEx_Request::clear_loginname() {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_->clear();
  }
  clear_has_loginname();
}
inline const ::std::string& PendingAccountEx_Request::loginname() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccountEx_Request.loginName)
  return *loginname_;
}
inline void PendingAccountEx_Request::set_loginname(const ::std::string& value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccountEx_Request.loginName)
}
inline void PendingAccountEx_Request::set_loginname(const char* value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.PendingAccountEx_Request.loginName)
}
inline void PendingAccountEx_Request::set_loginname(const char* value, size_t size) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.PendingAccountEx_Request.loginName)
}
inline ::std::string* PendingAccountEx_Request::mutable_loginname() {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.PendingAccountEx_Request.loginName)
  return loginname_;
}
inline ::std::string* PendingAccountEx_Request::release_loginname() {
  clear_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = loginname_;
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PendingAccountEx_Request::set_allocated_loginname(::std::string* loginname) {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete loginname_;
  }
  if (loginname) {
    set_has_loginname();
    loginname_ = loginname;
  } else {
    clear_has_loginname();
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.PendingAccountEx_Request.loginName)
}

// optional string accountName = 3;
inline bool PendingAccountEx_Request::has_accountname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PendingAccountEx_Request::set_has_accountname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PendingAccountEx_Request::clear_has_accountname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PendingAccountEx_Request::clear_accountname() {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_->clear();
  }
  clear_has_accountname();
}
inline const ::std::string& PendingAccountEx_Request::accountname() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccountEx_Request.accountName)
  return *accountname_;
}
inline void PendingAccountEx_Request::set_accountname(const ::std::string& value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccountEx_Request.accountName)
}
inline void PendingAccountEx_Request::set_accountname(const char* value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.PendingAccountEx_Request.accountName)
}
inline void PendingAccountEx_Request::set_accountname(const char* value, size_t size) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.PendingAccountEx_Request.accountName)
}
inline ::std::string* PendingAccountEx_Request::mutable_accountname() {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.PendingAccountEx_Request.accountName)
  return accountname_;
}
inline ::std::string* PendingAccountEx_Request::release_accountname() {
  clear_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = accountname_;
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PendingAccountEx_Request::set_allocated_accountname(::std::string* accountname) {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete accountname_;
  }
  if (accountname) {
    set_has_accountname();
    accountname_ = accountname;
  } else {
    clear_has_accountname();
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.PendingAccountEx_Request.accountName)
}

// optional string password = 4;
inline bool PendingAccountEx_Request::has_password() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PendingAccountEx_Request::set_has_password() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PendingAccountEx_Request::clear_has_password() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PendingAccountEx_Request::clear_password() {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& PendingAccountEx_Request::password() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccountEx_Request.password)
  return *password_;
}
inline void PendingAccountEx_Request::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccountEx_Request.password)
}
inline void PendingAccountEx_Request::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.PendingAccountEx_Request.password)
}
inline void PendingAccountEx_Request::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.PendingAccountEx_Request.password)
}
inline ::std::string* PendingAccountEx_Request::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.PendingAccountEx_Request.password)
  return password_;
}
inline ::std::string* PendingAccountEx_Request::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PendingAccountEx_Request::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.PendingAccountEx_Request.password)
}

// optional int32 entityID = 5;
inline bool PendingAccountEx_Request::has_entityid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PendingAccountEx_Request::set_has_entityid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PendingAccountEx_Request::clear_has_entityid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PendingAccountEx_Request::clear_entityid() {
  entityid_ = 0;
  clear_has_entityid();
}
inline ::google::protobuf::int32 PendingAccountEx_Request::entityid() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccountEx_Request.entityID)
  return entityid_;
}
inline void PendingAccountEx_Request::set_entityid(::google::protobuf::int32 value) {
  set_has_entityid();
  entityid_ = value;
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccountEx_Request.entityID)
}

// optional uint64 dbid = 6;
inline bool PendingAccountEx_Request::has_dbid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PendingAccountEx_Request::set_has_dbid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PendingAccountEx_Request::clear_has_dbid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PendingAccountEx_Request::clear_dbid() {
  dbid_ = GOOGLE_ULONGLONG(0);
  clear_has_dbid();
}
inline ::google::protobuf::uint64 PendingAccountEx_Request::dbid() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccountEx_Request.dbid)
  return dbid_;
}
inline void PendingAccountEx_Request::set_dbid(::google::protobuf::uint64 value) {
  set_has_dbid();
  dbid_ = value;
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccountEx_Request.dbid)
}

// optional uint32 flags = 7;
inline bool PendingAccountEx_Request::has_flags() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PendingAccountEx_Request::set_has_flags() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PendingAccountEx_Request::clear_has_flags() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PendingAccountEx_Request::clear_flags() {
  flags_ = 0u;
  clear_has_flags();
}
inline ::google::protobuf::uint32 PendingAccountEx_Request::flags() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccountEx_Request.flags)
  return flags_;
}
inline void PendingAccountEx_Request::set_flags(::google::protobuf::uint32 value) {
  set_has_flags();
  flags_ = value;
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccountEx_Request.flags)
}

// optional string extraData = 8;
inline bool PendingAccountEx_Request::has_extradata() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PendingAccountEx_Request::set_has_extradata() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PendingAccountEx_Request::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PendingAccountEx_Request::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& PendingAccountEx_Request::extradata() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.PendingAccountEx_Request.extraData)
  return *extradata_;
}
inline void PendingAccountEx_Request::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.PendingAccountEx_Request.extraData)
}
inline void PendingAccountEx_Request::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.PendingAccountEx_Request.extraData)
}
inline void PendingAccountEx_Request::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.PendingAccountEx_Request.extraData)
}
inline ::std::string* PendingAccountEx_Request::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.PendingAccountEx_Request.extraData)
  return extradata_;
}
inline ::std::string* PendingAccountEx_Request::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void PendingAccountEx_Request::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.PendingAccountEx_Request.extraData)
}

// -------------------------------------------------------------------

// LoginAccountBaseappAddr_Return

// optional string loginName = 1;
inline bool LoginAccountBaseappAddr_Return::has_loginname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginAccountBaseappAddr_Return::set_has_loginname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginAccountBaseappAddr_Return::clear_has_loginname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginAccountBaseappAddr_Return::clear_loginname() {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_->clear();
  }
  clear_has_loginname();
}
inline const ::std::string& LoginAccountBaseappAddr_Return::loginname() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.LoginAccountBaseappAddr_Return.loginName)
  return *loginname_;
}
inline void LoginAccountBaseappAddr_Return::set_loginname(const ::std::string& value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.LoginAccountBaseappAddr_Return.loginName)
}
inline void LoginAccountBaseappAddr_Return::set_loginname(const char* value) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.LoginAccountBaseappAddr_Return.loginName)
}
inline void LoginAccountBaseappAddr_Return::set_loginname(const char* value, size_t size) {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  loginname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.LoginAccountBaseappAddr_Return.loginName)
}
inline ::std::string* LoginAccountBaseappAddr_Return::mutable_loginname() {
  set_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    loginname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.LoginAccountBaseappAddr_Return.loginName)
  return loginname_;
}
inline ::std::string* LoginAccountBaseappAddr_Return::release_loginname() {
  clear_has_loginname();
  if (loginname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = loginname_;
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginAccountBaseappAddr_Return::set_allocated_loginname(::std::string* loginname) {
  if (loginname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete loginname_;
  }
  if (loginname) {
    set_has_loginname();
    loginname_ = loginname;
  } else {
    clear_has_loginname();
    loginname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.LoginAccountBaseappAddr_Return.loginName)
}

// optional string accountName = 2;
inline bool LoginAccountBaseappAddr_Return::has_accountname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginAccountBaseappAddr_Return::set_has_accountname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginAccountBaseappAddr_Return::clear_has_accountname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginAccountBaseappAddr_Return::clear_accountname() {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_->clear();
  }
  clear_has_accountname();
}
inline const ::std::string& LoginAccountBaseappAddr_Return::accountname() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.LoginAccountBaseappAddr_Return.accountName)
  return *accountname_;
}
inline void LoginAccountBaseappAddr_Return::set_accountname(const ::std::string& value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.LoginAccountBaseappAddr_Return.accountName)
}
inline void LoginAccountBaseappAddr_Return::set_accountname(const char* value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.LoginAccountBaseappAddr_Return.accountName)
}
inline void LoginAccountBaseappAddr_Return::set_accountname(const char* value, size_t size) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.LoginAccountBaseappAddr_Return.accountName)
}
inline ::std::string* LoginAccountBaseappAddr_Return::mutable_accountname() {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.LoginAccountBaseappAddr_Return.accountName)
  return accountname_;
}
inline ::std::string* LoginAccountBaseappAddr_Return::release_accountname() {
  clear_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = accountname_;
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginAccountBaseappAddr_Return::set_allocated_accountname(::std::string* accountname) {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete accountname_;
  }
  if (accountname) {
    set_has_accountname();
    accountname_ = accountname;
  } else {
    clear_has_accountname();
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.LoginAccountBaseappAddr_Return.accountName)
}

// optional string ip = 3;
inline bool LoginAccountBaseappAddr_Return::has_ip() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LoginAccountBaseappAddr_Return::set_has_ip() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LoginAccountBaseappAddr_Return::clear_has_ip() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LoginAccountBaseappAddr_Return::clear_ip() {
  if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_->clear();
  }
  clear_has_ip();
}
inline const ::std::string& LoginAccountBaseappAddr_Return::ip() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.LoginAccountBaseappAddr_Return.ip)
  return *ip_;
}
inline void LoginAccountBaseappAddr_Return::set_ip(const ::std::string& value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
  // @@protoc_insertion_point(field_set:basemgrlogin.LoginAccountBaseappAddr_Return.ip)
}
inline void LoginAccountBaseappAddr_Return::set_ip(const char* value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
  // @@protoc_insertion_point(field_set_char:basemgrlogin.LoginAccountBaseappAddr_Return.ip)
}
inline void LoginAccountBaseappAddr_Return::set_ip(const char* value, size_t size) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  ip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:basemgrlogin.LoginAccountBaseappAddr_Return.ip)
}
inline ::std::string* LoginAccountBaseappAddr_Return::mutable_ip() {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    ip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:basemgrlogin.LoginAccountBaseappAddr_Return.ip)
  return ip_;
}
inline ::std::string* LoginAccountBaseappAddr_Return::release_ip() {
  clear_has_ip();
  if (ip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = ip_;
    ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LoginAccountBaseappAddr_Return::set_allocated_ip(::std::string* ip) {
  if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ip_;
  }
  if (ip) {
    set_has_ip();
    ip_ = ip;
  } else {
    clear_has_ip();
    ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:basemgrlogin.LoginAccountBaseappAddr_Return.ip)
}

// optional uint32 port = 4;
inline bool LoginAccountBaseappAddr_Return::has_port() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LoginAccountBaseappAddr_Return::set_has_port() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LoginAccountBaseappAddr_Return::clear_has_port() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LoginAccountBaseappAddr_Return::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 LoginAccountBaseappAddr_Return::port() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.LoginAccountBaseappAddr_Return.port)
  return port_;
}
inline void LoginAccountBaseappAddr_Return::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:basemgrlogin.LoginAccountBaseappAddr_Return.port)
}

// -------------------------------------------------------------------

// BaseappInitProgress

// optional uint32 baseappsInitProgress = 1;
inline bool BaseappInitProgress::has_baseappsinitprogress() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BaseappInitProgress::set_has_baseappsinitprogress() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BaseappInitProgress::clear_has_baseappsinitprogress() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BaseappInitProgress::clear_baseappsinitprogress() {
  baseappsinitprogress_ = 0u;
  clear_has_baseappsinitprogress();
}
inline ::google::protobuf::uint32 BaseappInitProgress::baseappsinitprogress() const {
  // @@protoc_insertion_point(field_get:basemgrlogin.BaseappInitProgress.baseappsInitProgress)
  return baseappsinitprogress_;
}
inline void BaseappInitProgress::set_baseappsinitprogress(::google::protobuf::uint32 value) {
  set_has_baseappsinitprogress();
  baseappsinitprogress_ = value;
  // @@protoc_insertion_point(field_set:basemgrlogin.BaseappInitProgress.baseappsInitProgress)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace basemgrlogin

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_basemgrlogin_2eproto__INCLUDED
