// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientlogin.proto

#ifndef PROTOBUF_clientlogin_2eproto__INCLUDED
#define PROTOBUF_clientlogin_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace clientlogin {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_clientlogin_2eproto();
void protobuf_AssignDesc_clientlogin_2eproto();
void protobuf_ShutdownFile_clientlogin_2eproto();

class Hello_Request;
class Hello_Return;
class Login_Request;
class Login_Reutrn;

// ===================================================================

class Hello_Request : public ::google::protobuf::Message {
 public:
  Hello_Request();
  virtual ~Hello_Request();

  Hello_Request(const Hello_Request& from);

  inline Hello_Request& operator=(const Hello_Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Hello_Request& default_instance();

  void Swap(Hello_Request* other);

  // implements Message ----------------------------------------------

  Hello_Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Hello_Request& from);
  void MergeFrom(const Hello_Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // optional string extraData = 2;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 2;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:clientlogin.Hello_Request)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* extradata_;
  ::google::protobuf::uint32 version_;
  friend void  protobuf_AddDesc_clientlogin_2eproto();
  friend void protobuf_AssignDesc_clientlogin_2eproto();
  friend void protobuf_ShutdownFile_clientlogin_2eproto();

  void InitAsDefaultInstance();
  static Hello_Request* default_instance_;
};
// -------------------------------------------------------------------

class Hello_Return : public ::google::protobuf::Message {
 public:
  Hello_Return();
  virtual ~Hello_Return();

  Hello_Return(const Hello_Return& from);

  inline Hello_Return& operator=(const Hello_Return& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Hello_Return& default_instance();

  void Swap(Hello_Return* other);

  // implements Message ----------------------------------------------

  Hello_Return* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Hello_Return& from);
  void MergeFrom(const Hello_Return& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::uint32 result() const;
  inline void set_result(::google::protobuf::uint32 value);

  // optional uint32 version = 2;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 2;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // optional string extraData = 3;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 3;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:clientlogin.Hello_Return)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 result_;
  ::google::protobuf::uint32 version_;
  ::std::string* extradata_;
  friend void  protobuf_AddDesc_clientlogin_2eproto();
  friend void protobuf_AssignDesc_clientlogin_2eproto();
  friend void protobuf_ShutdownFile_clientlogin_2eproto();

  void InitAsDefaultInstance();
  static Hello_Return* default_instance_;
};
// -------------------------------------------------------------------

class Login_Request : public ::google::protobuf::Message {
 public:
  Login_Request();
  virtual ~Login_Request();

  Login_Request(const Login_Request& from);

  inline Login_Request& operator=(const Login_Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_Request& default_instance();

  void Swap(Login_Request* other);

  // implements Message ----------------------------------------------

  Login_Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_Request& from);
  void MergeFrom(const Login_Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 ctype = 1;
  inline bool has_ctype() const;
  inline void clear_ctype();
  static const int kCtypeFieldNumber = 1;
  inline ::google::protobuf::uint32 ctype() const;
  inline void set_ctype(::google::protobuf::uint32 value);

  // optional string account = 2;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 2;
  inline const ::std::string& account() const;
  inline void set_account(const ::std::string& value);
  inline void set_account(const char* value);
  inline void set_account(const char* value, size_t size);
  inline ::std::string* mutable_account();
  inline ::std::string* release_account();
  inline void set_allocated_account(::std::string* account);

  // optional string password = 3;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 3;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // optional string extraData = 4;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 4;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:clientlogin.Login_Request)
 private:
  inline void set_has_ctype();
  inline void clear_has_ctype();
  inline void set_has_account();
  inline void clear_has_account();
  inline void set_has_password();
  inline void clear_has_password();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* account_;
  ::std::string* password_;
  ::std::string* extradata_;
  ::google::protobuf::uint32 ctype_;
  friend void  protobuf_AddDesc_clientlogin_2eproto();
  friend void protobuf_AssignDesc_clientlogin_2eproto();
  friend void protobuf_ShutdownFile_clientlogin_2eproto();

  void InitAsDefaultInstance();
  static Login_Request* default_instance_;
};
// -------------------------------------------------------------------

class Login_Reutrn : public ::google::protobuf::Message {
 public:
  Login_Reutrn();
  virtual ~Login_Reutrn();

  Login_Reutrn(const Login_Reutrn& from);

  inline Login_Reutrn& operator=(const Login_Reutrn& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Login_Reutrn& default_instance();

  void Swap(Login_Reutrn* other);

  // implements Message ----------------------------------------------

  Login_Reutrn* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Login_Reutrn& from);
  void MergeFrom(const Login_Reutrn& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::uint32 result() const;
  inline void set_result(::google::protobuf::uint32 value);

  // optional string accountName = 2;
  inline bool has_accountname() const;
  inline void clear_accountname();
  static const int kAccountNameFieldNumber = 2;
  inline const ::std::string& accountname() const;
  inline void set_accountname(const ::std::string& value);
  inline void set_accountname(const char* value);
  inline void set_accountname(const char* value, size_t size);
  inline ::std::string* mutable_accountname();
  inline ::std::string* release_accountname();
  inline void set_allocated_accountname(::std::string* accountname);

  // optional string baseIp = 3;
  inline bool has_baseip() const;
  inline void clear_baseip();
  static const int kBaseIpFieldNumber = 3;
  inline const ::std::string& baseip() const;
  inline void set_baseip(const ::std::string& value);
  inline void set_baseip(const char* value);
  inline void set_baseip(const char* value, size_t size);
  inline ::std::string* mutable_baseip();
  inline ::std::string* release_baseip();
  inline void set_allocated_baseip(::std::string* baseip);

  // optional uint32 basePort = 4;
  inline bool has_baseport() const;
  inline void clear_baseport();
  static const int kBasePortFieldNumber = 4;
  inline ::google::protobuf::uint32 baseport() const;
  inline void set_baseport(::google::protobuf::uint32 value);

  // optional string extraData = 5;
  inline bool has_extradata() const;
  inline void clear_extradata();
  static const int kExtraDataFieldNumber = 5;
  inline const ::std::string& extradata() const;
  inline void set_extradata(const ::std::string& value);
  inline void set_extradata(const char* value);
  inline void set_extradata(const char* value, size_t size);
  inline ::std::string* mutable_extradata();
  inline ::std::string* release_extradata();
  inline void set_allocated_extradata(::std::string* extradata);

  // @@protoc_insertion_point(class_scope:clientlogin.Login_Reutrn)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_accountname();
  inline void clear_has_accountname();
  inline void set_has_baseip();
  inline void clear_has_baseip();
  inline void set_has_baseport();
  inline void clear_has_baseport();
  inline void set_has_extradata();
  inline void clear_has_extradata();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* accountname_;
  ::google::protobuf::uint32 result_;
  ::google::protobuf::uint32 baseport_;
  ::std::string* baseip_;
  ::std::string* extradata_;
  friend void  protobuf_AddDesc_clientlogin_2eproto();
  friend void protobuf_AssignDesc_clientlogin_2eproto();
  friend void protobuf_ShutdownFile_clientlogin_2eproto();

  void InitAsDefaultInstance();
  static Login_Reutrn* default_instance_;
};
// ===================================================================


// ===================================================================

// Hello_Request

// optional uint32 version = 1;
inline bool Hello_Request::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Hello_Request::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Hello_Request::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Hello_Request::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 Hello_Request::version() const {
  // @@protoc_insertion_point(field_get:clientlogin.Hello_Request.version)
  return version_;
}
inline void Hello_Request::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:clientlogin.Hello_Request.version)
}

// optional string extraData = 2;
inline bool Hello_Request::has_extradata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Hello_Request::set_has_extradata() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Hello_Request::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Hello_Request::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& Hello_Request::extradata() const {
  // @@protoc_insertion_point(field_get:clientlogin.Hello_Request.extraData)
  return *extradata_;
}
inline void Hello_Request::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:clientlogin.Hello_Request.extraData)
}
inline void Hello_Request::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:clientlogin.Hello_Request.extraData)
}
inline void Hello_Request::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clientlogin.Hello_Request.extraData)
}
inline ::std::string* Hello_Request::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:clientlogin.Hello_Request.extraData)
  return extradata_;
}
inline ::std::string* Hello_Request::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Hello_Request::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:clientlogin.Hello_Request.extraData)
}

// -------------------------------------------------------------------

// Hello_Return

// optional uint32 result = 1;
inline bool Hello_Return::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Hello_Return::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Hello_Return::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Hello_Return::clear_result() {
  result_ = 0u;
  clear_has_result();
}
inline ::google::protobuf::uint32 Hello_Return::result() const {
  // @@protoc_insertion_point(field_get:clientlogin.Hello_Return.result)
  return result_;
}
inline void Hello_Return::set_result(::google::protobuf::uint32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:clientlogin.Hello_Return.result)
}

// optional uint32 version = 2;
inline bool Hello_Return::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Hello_Return::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Hello_Return::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Hello_Return::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 Hello_Return::version() const {
  // @@protoc_insertion_point(field_get:clientlogin.Hello_Return.version)
  return version_;
}
inline void Hello_Return::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
  // @@protoc_insertion_point(field_set:clientlogin.Hello_Return.version)
}

// optional string extraData = 3;
inline bool Hello_Return::has_extradata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Hello_Return::set_has_extradata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Hello_Return::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Hello_Return::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& Hello_Return::extradata() const {
  // @@protoc_insertion_point(field_get:clientlogin.Hello_Return.extraData)
  return *extradata_;
}
inline void Hello_Return::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:clientlogin.Hello_Return.extraData)
}
inline void Hello_Return::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:clientlogin.Hello_Return.extraData)
}
inline void Hello_Return::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clientlogin.Hello_Return.extraData)
}
inline ::std::string* Hello_Return::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:clientlogin.Hello_Return.extraData)
  return extradata_;
}
inline ::std::string* Hello_Return::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Hello_Return::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:clientlogin.Hello_Return.extraData)
}

// -------------------------------------------------------------------

// Login_Request

// optional uint32 ctype = 1;
inline bool Login_Request::has_ctype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Login_Request::set_has_ctype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Login_Request::clear_has_ctype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Login_Request::clear_ctype() {
  ctype_ = 0u;
  clear_has_ctype();
}
inline ::google::protobuf::uint32 Login_Request::ctype() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Request.ctype)
  return ctype_;
}
inline void Login_Request::set_ctype(::google::protobuf::uint32 value) {
  set_has_ctype();
  ctype_ = value;
  // @@protoc_insertion_point(field_set:clientlogin.Login_Request.ctype)
}

// optional string account = 2;
inline bool Login_Request::has_account() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Login_Request::set_has_account() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Login_Request::clear_has_account() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Login_Request::clear_account() {
  if (account_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_->clear();
  }
  clear_has_account();
}
inline const ::std::string& Login_Request::account() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Request.account)
  return *account_;
}
inline void Login_Request::set_account(const ::std::string& value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_ = new ::std::string;
  }
  account_->assign(value);
  // @@protoc_insertion_point(field_set:clientlogin.Login_Request.account)
}
inline void Login_Request::set_account(const char* value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_ = new ::std::string;
  }
  account_->assign(value);
  // @@protoc_insertion_point(field_set_char:clientlogin.Login_Request.account)
}
inline void Login_Request::set_account(const char* value, size_t size) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_ = new ::std::string;
  }
  account_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clientlogin.Login_Request.account)
}
inline ::std::string* Login_Request::mutable_account() {
  set_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    account_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:clientlogin.Login_Request.account)
  return account_;
}
inline ::std::string* Login_Request::release_account() {
  clear_has_account();
  if (account_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = account_;
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login_Request::set_allocated_account(::std::string* account) {
  if (account_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete account_;
  }
  if (account) {
    set_has_account();
    account_ = account;
  } else {
    clear_has_account();
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:clientlogin.Login_Request.account)
}

// optional string password = 3;
inline bool Login_Request::has_password() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Login_Request::set_has_password() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Login_Request::clear_has_password() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Login_Request::clear_password() {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& Login_Request::password() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Request.password)
  return *password_;
}
inline void Login_Request::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set:clientlogin.Login_Request.password)
}
inline void Login_Request::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(value);
  // @@protoc_insertion_point(field_set_char:clientlogin.Login_Request.password)
}
inline void Login_Request::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clientlogin.Login_Request.password)
}
inline ::std::string* Login_Request::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    password_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:clientlogin.Login_Request.password)
  return password_;
}
inline ::std::string* Login_Request::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login_Request::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:clientlogin.Login_Request.password)
}

// optional string extraData = 4;
inline bool Login_Request::has_extradata() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Login_Request::set_has_extradata() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Login_Request::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Login_Request::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& Login_Request::extradata() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Request.extraData)
  return *extradata_;
}
inline void Login_Request::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:clientlogin.Login_Request.extraData)
}
inline void Login_Request::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:clientlogin.Login_Request.extraData)
}
inline void Login_Request::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clientlogin.Login_Request.extraData)
}
inline ::std::string* Login_Request::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:clientlogin.Login_Request.extraData)
  return extradata_;
}
inline ::std::string* Login_Request::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login_Request::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:clientlogin.Login_Request.extraData)
}

// -------------------------------------------------------------------

// Login_Reutrn

// optional uint32 result = 1;
inline bool Login_Reutrn::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Login_Reutrn::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Login_Reutrn::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Login_Reutrn::clear_result() {
  result_ = 0u;
  clear_has_result();
}
inline ::google::protobuf::uint32 Login_Reutrn::result() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Reutrn.result)
  return result_;
}
inline void Login_Reutrn::set_result(::google::protobuf::uint32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:clientlogin.Login_Reutrn.result)
}

// optional string accountName = 2;
inline bool Login_Reutrn::has_accountname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Login_Reutrn::set_has_accountname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Login_Reutrn::clear_has_accountname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Login_Reutrn::clear_accountname() {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_->clear();
  }
  clear_has_accountname();
}
inline const ::std::string& Login_Reutrn::accountname() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Reutrn.accountName)
  return *accountname_;
}
inline void Login_Reutrn::set_accountname(const ::std::string& value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set:clientlogin.Login_Reutrn.accountName)
}
inline void Login_Reutrn::set_accountname(const char* value) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(value);
  // @@protoc_insertion_point(field_set_char:clientlogin.Login_Reutrn.accountName)
}
inline void Login_Reutrn::set_accountname(const char* value, size_t size) {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  accountname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clientlogin.Login_Reutrn.accountName)
}
inline ::std::string* Login_Reutrn::mutable_accountname() {
  set_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    accountname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:clientlogin.Login_Reutrn.accountName)
  return accountname_;
}
inline ::std::string* Login_Reutrn::release_accountname() {
  clear_has_accountname();
  if (accountname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = accountname_;
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login_Reutrn::set_allocated_accountname(::std::string* accountname) {
  if (accountname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete accountname_;
  }
  if (accountname) {
    set_has_accountname();
    accountname_ = accountname;
  } else {
    clear_has_accountname();
    accountname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:clientlogin.Login_Reutrn.accountName)
}

// optional string baseIp = 3;
inline bool Login_Reutrn::has_baseip() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Login_Reutrn::set_has_baseip() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Login_Reutrn::clear_has_baseip() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Login_Reutrn::clear_baseip() {
  if (baseip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_->clear();
  }
  clear_has_baseip();
}
inline const ::std::string& Login_Reutrn::baseip() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Reutrn.baseIp)
  return *baseip_;
}
inline void Login_Reutrn::set_baseip(const ::std::string& value) {
  set_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_ = new ::std::string;
  }
  baseip_->assign(value);
  // @@protoc_insertion_point(field_set:clientlogin.Login_Reutrn.baseIp)
}
inline void Login_Reutrn::set_baseip(const char* value) {
  set_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_ = new ::std::string;
  }
  baseip_->assign(value);
  // @@protoc_insertion_point(field_set_char:clientlogin.Login_Reutrn.baseIp)
}
inline void Login_Reutrn::set_baseip(const char* value, size_t size) {
  set_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_ = new ::std::string;
  }
  baseip_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clientlogin.Login_Reutrn.baseIp)
}
inline ::std::string* Login_Reutrn::mutable_baseip() {
  set_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    baseip_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:clientlogin.Login_Reutrn.baseIp)
  return baseip_;
}
inline ::std::string* Login_Reutrn::release_baseip() {
  clear_has_baseip();
  if (baseip_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = baseip_;
    baseip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login_Reutrn::set_allocated_baseip(::std::string* baseip) {
  if (baseip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete baseip_;
  }
  if (baseip) {
    set_has_baseip();
    baseip_ = baseip;
  } else {
    clear_has_baseip();
    baseip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:clientlogin.Login_Reutrn.baseIp)
}

// optional uint32 basePort = 4;
inline bool Login_Reutrn::has_baseport() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Login_Reutrn::set_has_baseport() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Login_Reutrn::clear_has_baseport() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Login_Reutrn::clear_baseport() {
  baseport_ = 0u;
  clear_has_baseport();
}
inline ::google::protobuf::uint32 Login_Reutrn::baseport() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Reutrn.basePort)
  return baseport_;
}
inline void Login_Reutrn::set_baseport(::google::protobuf::uint32 value) {
  set_has_baseport();
  baseport_ = value;
  // @@protoc_insertion_point(field_set:clientlogin.Login_Reutrn.basePort)
}

// optional string extraData = 5;
inline bool Login_Reutrn::has_extradata() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Login_Reutrn::set_has_extradata() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Login_Reutrn::clear_has_extradata() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Login_Reutrn::clear_extradata() {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_->clear();
  }
  clear_has_extradata();
}
inline const ::std::string& Login_Reutrn::extradata() const {
  // @@protoc_insertion_point(field_get:clientlogin.Login_Reutrn.extraData)
  return *extradata_;
}
inline void Login_Reutrn::set_extradata(const ::std::string& value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set:clientlogin.Login_Reutrn.extraData)
}
inline void Login_Reutrn::set_extradata(const char* value) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(value);
  // @@protoc_insertion_point(field_set_char:clientlogin.Login_Reutrn.extraData)
}
inline void Login_Reutrn::set_extradata(const char* value, size_t size) {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  extradata_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clientlogin.Login_Reutrn.extraData)
}
inline ::std::string* Login_Reutrn::mutable_extradata() {
  set_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extradata_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:clientlogin.Login_Reutrn.extraData)
  return extradata_;
}
inline ::std::string* Login_Reutrn::release_extradata() {
  clear_has_extradata();
  if (extradata_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extradata_;
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Login_Reutrn::set_allocated_extradata(::std::string* extradata) {
  if (extradata_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extradata_;
  }
  if (extradata) {
    set_has_extradata();
    extradata_ = extradata;
  } else {
    clear_has_extradata();
    extradata_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:clientlogin.Login_Reutrn.extraData)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace clientlogin

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_clientlogin_2eproto__INCLUDED
