// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace common {

namespace {

const ::google::protobuf::Descriptor* RegisterServer_Request_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RegisterServer_Request_reflection_ = NULL;
const ::google::protobuf::Descriptor* RegisterServer_Return_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  RegisterServer_Return_reflection_ = NULL;
const ::google::protobuf::Descriptor* ActiveTick_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ActiveTick_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_common_2eproto() {
  protobuf_AddDesc_common_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "common.proto");
  GOOGLE_CHECK(file != NULL);
  RegisterServer_Request_descriptor_ = file->message_type(0);
  static const int RegisterServer_Request_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, componenttype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, componentid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, extaddr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, extport_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, intaddr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, intport_),
  };
  RegisterServer_Request_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RegisterServer_Request_descriptor_,
      RegisterServer_Request::default_instance_,
      RegisterServer_Request_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Request, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RegisterServer_Request));
  RegisterServer_Return_descriptor_ = file->message_type(1);
  static const int RegisterServer_Return_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, componenttype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, componentid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, intaddr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, intport_),
  };
  RegisterServer_Return_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      RegisterServer_Return_descriptor_,
      RegisterServer_Return::default_instance_,
      RegisterServer_Return_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RegisterServer_Return, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(RegisterServer_Return));
  ActiveTick_descriptor_ = file->message_type(2);
  static const int ActiveTick_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ActiveTick, componenttype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ActiveTick, componentid_),
  };
  ActiveTick_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ActiveTick_descriptor_,
      ActiveTick::default_instance_,
      ActiveTick_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ActiveTick, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ActiveTick, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ActiveTick));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_common_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RegisterServer_Request_descriptor_, &RegisterServer_Request::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    RegisterServer_Return_descriptor_, &RegisterServer_Return::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ActiveTick_descriptor_, &ActiveTick::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_common_2eproto() {
  delete RegisterServer_Request::default_instance_;
  delete RegisterServer_Request_reflection_;
  delete RegisterServer_Return::default_instance_;
  delete RegisterServer_Return_reflection_;
  delete ActiveTick::default_instance_;
  delete ActiveTick_reflection_;
}

void protobuf_AddDesc_common_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014common.proto\022\006common\"\247\001\n\026RegisterServe"
    "r_Request\022\025\n\rcomponentType\030\001 \001(\005\022\013\n\003uid\030"
    "\002 \001(\005\022\020\n\010username\030\003 \001(\t\022\023\n\013componentID\030\004"
    " \001(\003\022\017\n\007extaddr\030\005 \001(\005\022\017\n\007extport\030\006 \001(\005\022\017"
    "\n\007intaddr\030\007 \001(\005\022\017\n\007intport\030\010 \001(\005\"\224\001\n\025Reg"
    "isterServer_Return\022\016\n\006result\030\001 \002(\005\022\025\n\rco"
    "mponentType\030\002 \001(\005\022\013\n\003uid\030\003 \001(\005\022\020\n\010userna"
    "me\030\004 \001(\t\022\023\n\013componentID\030\005 \001(\003\022\017\n\007intaddr"
    "\030\006 \001(\005\022\017\n\007intport\030\007 \001(\005\"8\n\nActiveTick\022\025\n"
    "\rcomponentType\030\001 \001(\005\022\023\n\013componentID\030\002 \001("
    "\003", 401);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "common.proto", &protobuf_RegisterTypes);
  RegisterServer_Request::default_instance_ = new RegisterServer_Request();
  RegisterServer_Return::default_instance_ = new RegisterServer_Return();
  ActiveTick::default_instance_ = new ActiveTick();
  RegisterServer_Request::default_instance_->InitAsDefaultInstance();
  RegisterServer_Return::default_instance_->InitAsDefaultInstance();
  ActiveTick::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_common_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_common_2eproto {
  StaticDescriptorInitializer_common_2eproto() {
    protobuf_AddDesc_common_2eproto();
  }
} static_descriptor_initializer_common_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int RegisterServer_Request::kComponentTypeFieldNumber;
const int RegisterServer_Request::kUidFieldNumber;
const int RegisterServer_Request::kUsernameFieldNumber;
const int RegisterServer_Request::kComponentIDFieldNumber;
const int RegisterServer_Request::kExtaddrFieldNumber;
const int RegisterServer_Request::kExtportFieldNumber;
const int RegisterServer_Request::kIntaddrFieldNumber;
const int RegisterServer_Request::kIntportFieldNumber;
#endif  // !_MSC_VER

RegisterServer_Request::RegisterServer_Request()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:common.RegisterServer_Request)
}

void RegisterServer_Request::InitAsDefaultInstance() {
}

RegisterServer_Request::RegisterServer_Request(const RegisterServer_Request& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:common.RegisterServer_Request)
}

void RegisterServer_Request::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  componenttype_ = 0;
  uid_ = 0;
  username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  componentid_ = GOOGLE_LONGLONG(0);
  extaddr_ = 0;
  extport_ = 0;
  intaddr_ = 0;
  intport_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RegisterServer_Request::~RegisterServer_Request() {
  // @@protoc_insertion_point(destructor:common.RegisterServer_Request)
  SharedDtor();
}

void RegisterServer_Request::SharedDtor() {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete username_;
  }
  if (this != default_instance_) {
  }
}

void RegisterServer_Request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RegisterServer_Request::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RegisterServer_Request_descriptor_;
}

const RegisterServer_Request& RegisterServer_Request::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2eproto();
  return *default_instance_;
}

RegisterServer_Request* RegisterServer_Request::default_instance_ = NULL;

RegisterServer_Request* RegisterServer_Request::New() const {
  return new RegisterServer_Request;
}

void RegisterServer_Request::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<RegisterServer_Request*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(componenttype_, uid_);
    ZR_(componentid_, intport_);
    if (has_username()) {
      if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        username_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RegisterServer_Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:common.RegisterServer_Request)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 componentType = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &componenttype_)));
          set_has_componenttype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_uid;
        break;
      }

      // optional int32 uid = 2;
      case 2: {
        if (tag == 16) {
         parse_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_username;
        break;
      }

      // optional string username = 3;
      case 3: {
        if (tag == 26) {
         parse_username:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "username");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_componentID;
        break;
      }

      // optional int64 componentID = 4;
      case 4: {
        if (tag == 32) {
         parse_componentID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &componentid_)));
          set_has_componentid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_extaddr;
        break;
      }

      // optional int32 extaddr = 5;
      case 5: {
        if (tag == 40) {
         parse_extaddr:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &extaddr_)));
          set_has_extaddr();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_extport;
        break;
      }

      // optional int32 extport = 6;
      case 6: {
        if (tag == 48) {
         parse_extport:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &extport_)));
          set_has_extport();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_intaddr;
        break;
      }

      // optional int32 intaddr = 7;
      case 7: {
        if (tag == 56) {
         parse_intaddr:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intaddr_)));
          set_has_intaddr();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_intport;
        break;
      }

      // optional int32 intport = 8;
      case 8: {
        if (tag == 64) {
         parse_intport:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intport_)));
          set_has_intport();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:common.RegisterServer_Request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:common.RegisterServer_Request)
  return false;
#undef DO_
}

void RegisterServer_Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:common.RegisterServer_Request)
  // optional int32 componentType = 1;
  if (has_componenttype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->componenttype(), output);
  }

  // optional int32 uid = 2;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->uid(), output);
  }

  // optional string username = 3;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->username(), output);
  }

  // optional int64 componentID = 4;
  if (has_componentid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->componentid(), output);
  }

  // optional int32 extaddr = 5;
  if (has_extaddr()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->extaddr(), output);
  }

  // optional int32 extport = 6;
  if (has_extport()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->extport(), output);
  }

  // optional int32 intaddr = 7;
  if (has_intaddr()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->intaddr(), output);
  }

  // optional int32 intport = 8;
  if (has_intport()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->intport(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:common.RegisterServer_Request)
}

::google::protobuf::uint8* RegisterServer_Request::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:common.RegisterServer_Request)
  // optional int32 componentType = 1;
  if (has_componenttype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->componenttype(), target);
  }

  // optional int32 uid = 2;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->uid(), target);
  }

  // optional string username = 3;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "username");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->username(), target);
  }

  // optional int64 componentID = 4;
  if (has_componentid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->componentid(), target);
  }

  // optional int32 extaddr = 5;
  if (has_extaddr()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->extaddr(), target);
  }

  // optional int32 extport = 6;
  if (has_extport()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->extport(), target);
  }

  // optional int32 intaddr = 7;
  if (has_intaddr()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->intaddr(), target);
  }

  // optional int32 intport = 8;
  if (has_intport()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->intport(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:common.RegisterServer_Request)
  return target;
}

int RegisterServer_Request::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 componentType = 1;
    if (has_componenttype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->componenttype());
    }

    // optional int32 uid = 2;
    if (has_uid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->uid());
    }

    // optional string username = 3;
    if (has_username()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->username());
    }

    // optional int64 componentID = 4;
    if (has_componentid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->componentid());
    }

    // optional int32 extaddr = 5;
    if (has_extaddr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->extaddr());
    }

    // optional int32 extport = 6;
    if (has_extport()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->extport());
    }

    // optional int32 intaddr = 7;
    if (has_intaddr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->intaddr());
    }

    // optional int32 intport = 8;
    if (has_intport()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->intport());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RegisterServer_Request::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RegisterServer_Request* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RegisterServer_Request*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RegisterServer_Request::MergeFrom(const RegisterServer_Request& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_componenttype()) {
      set_componenttype(from.componenttype());
    }
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_username()) {
      set_username(from.username());
    }
    if (from.has_componentid()) {
      set_componentid(from.componentid());
    }
    if (from.has_extaddr()) {
      set_extaddr(from.extaddr());
    }
    if (from.has_extport()) {
      set_extport(from.extport());
    }
    if (from.has_intaddr()) {
      set_intaddr(from.intaddr());
    }
    if (from.has_intport()) {
      set_intport(from.intport());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RegisterServer_Request::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RegisterServer_Request::CopyFrom(const RegisterServer_Request& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegisterServer_Request::IsInitialized() const {

  return true;
}

void RegisterServer_Request::Swap(RegisterServer_Request* other) {
  if (other != this) {
    std::swap(componenttype_, other->componenttype_);
    std::swap(uid_, other->uid_);
    std::swap(username_, other->username_);
    std::swap(componentid_, other->componentid_);
    std::swap(extaddr_, other->extaddr_);
    std::swap(extport_, other->extport_);
    std::swap(intaddr_, other->intaddr_);
    std::swap(intport_, other->intport_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RegisterServer_Request::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RegisterServer_Request_descriptor_;
  metadata.reflection = RegisterServer_Request_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int RegisterServer_Return::kResultFieldNumber;
const int RegisterServer_Return::kComponentTypeFieldNumber;
const int RegisterServer_Return::kUidFieldNumber;
const int RegisterServer_Return::kUsernameFieldNumber;
const int RegisterServer_Return::kComponentIDFieldNumber;
const int RegisterServer_Return::kIntaddrFieldNumber;
const int RegisterServer_Return::kIntportFieldNumber;
#endif  // !_MSC_VER

RegisterServer_Return::RegisterServer_Return()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:common.RegisterServer_Return)
}

void RegisterServer_Return::InitAsDefaultInstance() {
}

RegisterServer_Return::RegisterServer_Return(const RegisterServer_Return& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:common.RegisterServer_Return)
}

void RegisterServer_Return::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  result_ = 0;
  componenttype_ = 0;
  uid_ = 0;
  username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  componentid_ = GOOGLE_LONGLONG(0);
  intaddr_ = 0;
  intport_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

RegisterServer_Return::~RegisterServer_Return() {
  // @@protoc_insertion_point(destructor:common.RegisterServer_Return)
  SharedDtor();
}

void RegisterServer_Return::SharedDtor() {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete username_;
  }
  if (this != default_instance_) {
  }
}

void RegisterServer_Return::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RegisterServer_Return::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return RegisterServer_Return_descriptor_;
}

const RegisterServer_Return& RegisterServer_Return::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2eproto();
  return *default_instance_;
}

RegisterServer_Return* RegisterServer_Return::default_instance_ = NULL;

RegisterServer_Return* RegisterServer_Return::New() const {
  return new RegisterServer_Return;
}

void RegisterServer_Return::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<RegisterServer_Return*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 127) {
    ZR_(result_, componenttype_);
    ZR_(uid_, intport_);
    if (has_username()) {
      if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        username_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool RegisterServer_Return::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:common.RegisterServer_Return)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 result = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
          set_has_result();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_componentType;
        break;
      }

      // optional int32 componentType = 2;
      case 2: {
        if (tag == 16) {
         parse_componentType:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &componenttype_)));
          set_has_componenttype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_uid;
        break;
      }

      // optional int32 uid = 3;
      case 3: {
        if (tag == 24) {
         parse_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_username;
        break;
      }

      // optional string username = 4;
      case 4: {
        if (tag == 34) {
         parse_username:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "username");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_componentID;
        break;
      }

      // optional int64 componentID = 5;
      case 5: {
        if (tag == 40) {
         parse_componentID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &componentid_)));
          set_has_componentid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_intaddr;
        break;
      }

      // optional int32 intaddr = 6;
      case 6: {
        if (tag == 48) {
         parse_intaddr:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intaddr_)));
          set_has_intaddr();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_intport;
        break;
      }

      // optional int32 intport = 7;
      case 7: {
        if (tag == 56) {
         parse_intport:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intport_)));
          set_has_intport();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:common.RegisterServer_Return)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:common.RegisterServer_Return)
  return false;
#undef DO_
}

void RegisterServer_Return::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:common.RegisterServer_Return)
  // required int32 result = 1;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // optional int32 componentType = 2;
  if (has_componenttype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->componenttype(), output);
  }

  // optional int32 uid = 3;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->uid(), output);
  }

  // optional string username = 4;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->username(), output);
  }

  // optional int64 componentID = 5;
  if (has_componentid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->componentid(), output);
  }

  // optional int32 intaddr = 6;
  if (has_intaddr()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->intaddr(), output);
  }

  // optional int32 intport = 7;
  if (has_intport()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->intport(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:common.RegisterServer_Return)
}

::google::protobuf::uint8* RegisterServer_Return::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:common.RegisterServer_Return)
  // required int32 result = 1;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // optional int32 componentType = 2;
  if (has_componenttype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->componenttype(), target);
  }

  // optional int32 uid = 3;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->uid(), target);
  }

  // optional string username = 4;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "username");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->username(), target);
  }

  // optional int64 componentID = 5;
  if (has_componentid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->componentid(), target);
  }

  // optional int32 intaddr = 6;
  if (has_intaddr()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->intaddr(), target);
  }

  // optional int32 intport = 7;
  if (has_intport()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->intport(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:common.RegisterServer_Return)
  return target;
}

int RegisterServer_Return::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 result = 1;
    if (has_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->result());
    }

    // optional int32 componentType = 2;
    if (has_componenttype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->componenttype());
    }

    // optional int32 uid = 3;
    if (has_uid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->uid());
    }

    // optional string username = 4;
    if (has_username()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->username());
    }

    // optional int64 componentID = 5;
    if (has_componentid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->componentid());
    }

    // optional int32 intaddr = 6;
    if (has_intaddr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->intaddr());
    }

    // optional int32 intport = 7;
    if (has_intport()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->intport());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RegisterServer_Return::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const RegisterServer_Return* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const RegisterServer_Return*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void RegisterServer_Return::MergeFrom(const RegisterServer_Return& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
    if (from.has_componenttype()) {
      set_componenttype(from.componenttype());
    }
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_username()) {
      set_username(from.username());
    }
    if (from.has_componentid()) {
      set_componentid(from.componentid());
    }
    if (from.has_intaddr()) {
      set_intaddr(from.intaddr());
    }
    if (from.has_intport()) {
      set_intport(from.intport());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void RegisterServer_Return::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RegisterServer_Return::CopyFrom(const RegisterServer_Return& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegisterServer_Return::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void RegisterServer_Return::Swap(RegisterServer_Return* other) {
  if (other != this) {
    std::swap(result_, other->result_);
    std::swap(componenttype_, other->componenttype_);
    std::swap(uid_, other->uid_);
    std::swap(username_, other->username_);
    std::swap(componentid_, other->componentid_);
    std::swap(intaddr_, other->intaddr_);
    std::swap(intport_, other->intport_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata RegisterServer_Return::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = RegisterServer_Return_descriptor_;
  metadata.reflection = RegisterServer_Return_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ActiveTick::kComponentTypeFieldNumber;
const int ActiveTick::kComponentIDFieldNumber;
#endif  // !_MSC_VER

ActiveTick::ActiveTick()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:common.ActiveTick)
}

void ActiveTick::InitAsDefaultInstance() {
}

ActiveTick::ActiveTick(const ActiveTick& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:common.ActiveTick)
}

void ActiveTick::SharedCtor() {
  _cached_size_ = 0;
  componenttype_ = 0;
  componentid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ActiveTick::~ActiveTick() {
  // @@protoc_insertion_point(destructor:common.ActiveTick)
  SharedDtor();
}

void ActiveTick::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ActiveTick::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ActiveTick::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ActiveTick_descriptor_;
}

const ActiveTick& ActiveTick::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_common_2eproto();
  return *default_instance_;
}

ActiveTick* ActiveTick::default_instance_ = NULL;

ActiveTick* ActiveTick::New() const {
  return new ActiveTick;
}

void ActiveTick::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ActiveTick*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(componentid_, componenttype_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ActiveTick::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:common.ActiveTick)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 componentType = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &componenttype_)));
          set_has_componenttype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_componentID;
        break;
      }

      // optional int64 componentID = 2;
      case 2: {
        if (tag == 16) {
         parse_componentID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &componentid_)));
          set_has_componentid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:common.ActiveTick)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:common.ActiveTick)
  return false;
#undef DO_
}

void ActiveTick::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:common.ActiveTick)
  // optional int32 componentType = 1;
  if (has_componenttype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->componenttype(), output);
  }

  // optional int64 componentID = 2;
  if (has_componentid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->componentid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:common.ActiveTick)
}

::google::protobuf::uint8* ActiveTick::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:common.ActiveTick)
  // optional int32 componentType = 1;
  if (has_componenttype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->componenttype(), target);
  }

  // optional int64 componentID = 2;
  if (has_componentid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->componentid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:common.ActiveTick)
  return target;
}

int ActiveTick::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 componentType = 1;
    if (has_componenttype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->componenttype());
    }

    // optional int64 componentID = 2;
    if (has_componentid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->componentid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ActiveTick::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ActiveTick* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ActiveTick*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ActiveTick::MergeFrom(const ActiveTick& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_componenttype()) {
      set_componenttype(from.componenttype());
    }
    if (from.has_componentid()) {
      set_componentid(from.componentid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ActiveTick::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ActiveTick::CopyFrom(const ActiveTick& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActiveTick::IsInitialized() const {

  return true;
}

void ActiveTick::Swap(ActiveTick* other) {
  if (other != this) {
    std::swap(componenttype_, other->componenttype_);
    std::swap(componentid_, other->componentid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ActiveTick::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ActiveTick_descriptor_;
  metadata.reflection = ActiveTick_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace common

// @@protoc_insertion_point(global_scope)
