// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

#ifndef PROTOBUF_common_2eproto__INCLUDED
#define PROTOBUF_common_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace common {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_common_2eproto();
void protobuf_AssignDesc_common_2eproto();
void protobuf_ShutdownFile_common_2eproto();

class RegisterServer_Request;
class RegisterServer_Return;
class ActiveTick;

// ===================================================================

class RegisterServer_Request : public ::google::protobuf::Message {
 public:
  RegisterServer_Request();
  virtual ~RegisterServer_Request();

  RegisterServer_Request(const RegisterServer_Request& from);

  inline RegisterServer_Request& operator=(const RegisterServer_Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterServer_Request& default_instance();

  void Swap(RegisterServer_Request* other);

  // implements Message ----------------------------------------------

  RegisterServer_Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegisterServer_Request& from);
  void MergeFrom(const RegisterServer_Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 componentType = 1;
  inline bool has_componenttype() const;
  inline void clear_componenttype();
  static const int kComponentTypeFieldNumber = 1;
  inline ::google::protobuf::int32 componenttype() const;
  inline void set_componenttype(::google::protobuf::int32 value);

  // optional int32 uid = 2;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 2;
  inline ::google::protobuf::int32 uid() const;
  inline void set_uid(::google::protobuf::int32 value);

  // optional string username = 3;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUsernameFieldNumber = 3;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // optional int64 componentID = 4;
  inline bool has_componentid() const;
  inline void clear_componentid();
  static const int kComponentIDFieldNumber = 4;
  inline ::google::protobuf::int64 componentid() const;
  inline void set_componentid(::google::protobuf::int64 value);

  // optional int32 extaddr = 5;
  inline bool has_extaddr() const;
  inline void clear_extaddr();
  static const int kExtaddrFieldNumber = 5;
  inline ::google::protobuf::int32 extaddr() const;
  inline void set_extaddr(::google::protobuf::int32 value);

  // optional int32 extport = 6;
  inline bool has_extport() const;
  inline void clear_extport();
  static const int kExtportFieldNumber = 6;
  inline ::google::protobuf::int32 extport() const;
  inline void set_extport(::google::protobuf::int32 value);

  // optional int32 intaddr = 7;
  inline bool has_intaddr() const;
  inline void clear_intaddr();
  static const int kIntaddrFieldNumber = 7;
  inline ::google::protobuf::int32 intaddr() const;
  inline void set_intaddr(::google::protobuf::int32 value);

  // optional int32 intport = 8;
  inline bool has_intport() const;
  inline void clear_intport();
  static const int kIntportFieldNumber = 8;
  inline ::google::protobuf::int32 intport() const;
  inline void set_intport(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:common.RegisterServer_Request)
 private:
  inline void set_has_componenttype();
  inline void clear_has_componenttype();
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_componentid();
  inline void clear_has_componentid();
  inline void set_has_extaddr();
  inline void clear_has_extaddr();
  inline void set_has_extport();
  inline void clear_has_extport();
  inline void set_has_intaddr();
  inline void clear_has_intaddr();
  inline void set_has_intport();
  inline void clear_has_intport();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 componenttype_;
  ::google::protobuf::int32 uid_;
  ::std::string* username_;
  ::google::protobuf::int64 componentid_;
  ::google::protobuf::int32 extaddr_;
  ::google::protobuf::int32 extport_;
  ::google::protobuf::int32 intaddr_;
  ::google::protobuf::int32 intport_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static RegisterServer_Request* default_instance_;
};
// -------------------------------------------------------------------

class RegisterServer_Return : public ::google::protobuf::Message {
 public:
  RegisterServer_Return();
  virtual ~RegisterServer_Return();

  RegisterServer_Return(const RegisterServer_Return& from);

  inline RegisterServer_Return& operator=(const RegisterServer_Return& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterServer_Return& default_instance();

  void Swap(RegisterServer_Return* other);

  // implements Message ----------------------------------------------

  RegisterServer_Return* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegisterServer_Return& from);
  void MergeFrom(const RegisterServer_Return& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // optional int32 componentType = 2;
  inline bool has_componenttype() const;
  inline void clear_componenttype();
  static const int kComponentTypeFieldNumber = 2;
  inline ::google::protobuf::int32 componenttype() const;
  inline void set_componenttype(::google::protobuf::int32 value);

  // optional int32 uid = 3;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 3;
  inline ::google::protobuf::int32 uid() const;
  inline void set_uid(::google::protobuf::int32 value);

  // optional string username = 4;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUsernameFieldNumber = 4;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // optional int64 componentID = 5;
  inline bool has_componentid() const;
  inline void clear_componentid();
  static const int kComponentIDFieldNumber = 5;
  inline ::google::protobuf::int64 componentid() const;
  inline void set_componentid(::google::protobuf::int64 value);

  // optional int32 intaddr = 6;
  inline bool has_intaddr() const;
  inline void clear_intaddr();
  static const int kIntaddrFieldNumber = 6;
  inline ::google::protobuf::int32 intaddr() const;
  inline void set_intaddr(::google::protobuf::int32 value);

  // optional int32 intport = 7;
  inline bool has_intport() const;
  inline void clear_intport();
  static const int kIntportFieldNumber = 7;
  inline ::google::protobuf::int32 intport() const;
  inline void set_intport(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:common.RegisterServer_Return)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_componenttype();
  inline void clear_has_componenttype();
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_componentid();
  inline void clear_has_componentid();
  inline void set_has_intaddr();
  inline void clear_has_intaddr();
  inline void set_has_intport();
  inline void clear_has_intport();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 componenttype_;
  ::std::string* username_;
  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 intaddr_;
  ::google::protobuf::int64 componentid_;
  ::google::protobuf::int32 intport_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static RegisterServer_Return* default_instance_;
};
// -------------------------------------------------------------------

class ActiveTick : public ::google::protobuf::Message {
 public:
  ActiveTick();
  virtual ~ActiveTick();

  ActiveTick(const ActiveTick& from);

  inline ActiveTick& operator=(const ActiveTick& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ActiveTick& default_instance();

  void Swap(ActiveTick* other);

  // implements Message ----------------------------------------------

  ActiveTick* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ActiveTick& from);
  void MergeFrom(const ActiveTick& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 componentType = 1;
  inline bool has_componenttype() const;
  inline void clear_componenttype();
  static const int kComponentTypeFieldNumber = 1;
  inline ::google::protobuf::int32 componenttype() const;
  inline void set_componenttype(::google::protobuf::int32 value);

  // optional int64 componentID = 2;
  inline bool has_componentid() const;
  inline void clear_componentid();
  static const int kComponentIDFieldNumber = 2;
  inline ::google::protobuf::int64 componentid() const;
  inline void set_componentid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:common.ActiveTick)
 private:
  inline void set_has_componenttype();
  inline void clear_has_componenttype();
  inline void set_has_componentid();
  inline void clear_has_componentid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 componentid_;
  ::google::protobuf::int32 componenttype_;
  friend void  protobuf_AddDesc_common_2eproto();
  friend void protobuf_AssignDesc_common_2eproto();
  friend void protobuf_ShutdownFile_common_2eproto();

  void InitAsDefaultInstance();
  static ActiveTick* default_instance_;
};
// ===================================================================


// ===================================================================

// RegisterServer_Request

// optional int32 componentType = 1;
inline bool RegisterServer_Request::has_componenttype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterServer_Request::set_has_componenttype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterServer_Request::clear_has_componenttype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterServer_Request::clear_componenttype() {
  componenttype_ = 0;
  clear_has_componenttype();
}
inline ::google::protobuf::int32 RegisterServer_Request::componenttype() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Request.componentType)
  return componenttype_;
}
inline void RegisterServer_Request::set_componenttype(::google::protobuf::int32 value) {
  set_has_componenttype();
  componenttype_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Request.componentType)
}

// optional int32 uid = 2;
inline bool RegisterServer_Request::has_uid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegisterServer_Request::set_has_uid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegisterServer_Request::clear_has_uid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegisterServer_Request::clear_uid() {
  uid_ = 0;
  clear_has_uid();
}
inline ::google::protobuf::int32 RegisterServer_Request::uid() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Request.uid)
  return uid_;
}
inline void RegisterServer_Request::set_uid(::google::protobuf::int32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Request.uid)
}

// optional string username = 3;
inline bool RegisterServer_Request::has_username() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RegisterServer_Request::set_has_username() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RegisterServer_Request::clear_has_username() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RegisterServer_Request::clear_username() {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& RegisterServer_Request::username() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Request.username)
  return *username_;
}
inline void RegisterServer_Request::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set:common.RegisterServer_Request.username)
}
inline void RegisterServer_Request::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set_char:common.RegisterServer_Request.username)
}
inline void RegisterServer_Request::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:common.RegisterServer_Request.username)
}
inline ::std::string* RegisterServer_Request::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:common.RegisterServer_Request.username)
  return username_;
}
inline ::std::string* RegisterServer_Request::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterServer_Request::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:common.RegisterServer_Request.username)
}

// optional int64 componentID = 4;
inline bool RegisterServer_Request::has_componentid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RegisterServer_Request::set_has_componentid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RegisterServer_Request::clear_has_componentid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RegisterServer_Request::clear_componentid() {
  componentid_ = GOOGLE_LONGLONG(0);
  clear_has_componentid();
}
inline ::google::protobuf::int64 RegisterServer_Request::componentid() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Request.componentID)
  return componentid_;
}
inline void RegisterServer_Request::set_componentid(::google::protobuf::int64 value) {
  set_has_componentid();
  componentid_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Request.componentID)
}

// optional int32 extaddr = 5;
inline bool RegisterServer_Request::has_extaddr() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RegisterServer_Request::set_has_extaddr() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RegisterServer_Request::clear_has_extaddr() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RegisterServer_Request::clear_extaddr() {
  extaddr_ = 0;
  clear_has_extaddr();
}
inline ::google::protobuf::int32 RegisterServer_Request::extaddr() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Request.extaddr)
  return extaddr_;
}
inline void RegisterServer_Request::set_extaddr(::google::protobuf::int32 value) {
  set_has_extaddr();
  extaddr_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Request.extaddr)
}

// optional int32 extport = 6;
inline bool RegisterServer_Request::has_extport() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RegisterServer_Request::set_has_extport() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RegisterServer_Request::clear_has_extport() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RegisterServer_Request::clear_extport() {
  extport_ = 0;
  clear_has_extport();
}
inline ::google::protobuf::int32 RegisterServer_Request::extport() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Request.extport)
  return extport_;
}
inline void RegisterServer_Request::set_extport(::google::protobuf::int32 value) {
  set_has_extport();
  extport_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Request.extport)
}

// optional int32 intaddr = 7;
inline bool RegisterServer_Request::has_intaddr() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RegisterServer_Request::set_has_intaddr() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RegisterServer_Request::clear_has_intaddr() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RegisterServer_Request::clear_intaddr() {
  intaddr_ = 0;
  clear_has_intaddr();
}
inline ::google::protobuf::int32 RegisterServer_Request::intaddr() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Request.intaddr)
  return intaddr_;
}
inline void RegisterServer_Request::set_intaddr(::google::protobuf::int32 value) {
  set_has_intaddr();
  intaddr_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Request.intaddr)
}

// optional int32 intport = 8;
inline bool RegisterServer_Request::has_intport() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RegisterServer_Request::set_has_intport() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RegisterServer_Request::clear_has_intport() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RegisterServer_Request::clear_intport() {
  intport_ = 0;
  clear_has_intport();
}
inline ::google::protobuf::int32 RegisterServer_Request::intport() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Request.intport)
  return intport_;
}
inline void RegisterServer_Request::set_intport(::google::protobuf::int32 value) {
  set_has_intport();
  intport_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Request.intport)
}

// -------------------------------------------------------------------

// RegisterServer_Return

// required int32 result = 1;
inline bool RegisterServer_Return::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterServer_Return::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterServer_Return::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterServer_Return::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 RegisterServer_Return::result() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Return.result)
  return result_;
}
inline void RegisterServer_Return::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Return.result)
}

// optional int32 componentType = 2;
inline bool RegisterServer_Return::has_componenttype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegisterServer_Return::set_has_componenttype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegisterServer_Return::clear_has_componenttype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegisterServer_Return::clear_componenttype() {
  componenttype_ = 0;
  clear_has_componenttype();
}
inline ::google::protobuf::int32 RegisterServer_Return::componenttype() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Return.componentType)
  return componenttype_;
}
inline void RegisterServer_Return::set_componenttype(::google::protobuf::int32 value) {
  set_has_componenttype();
  componenttype_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Return.componentType)
}

// optional int32 uid = 3;
inline bool RegisterServer_Return::has_uid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RegisterServer_Return::set_has_uid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RegisterServer_Return::clear_has_uid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RegisterServer_Return::clear_uid() {
  uid_ = 0;
  clear_has_uid();
}
inline ::google::protobuf::int32 RegisterServer_Return::uid() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Return.uid)
  return uid_;
}
inline void RegisterServer_Return::set_uid(::google::protobuf::int32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Return.uid)
}

// optional string username = 4;
inline bool RegisterServer_Return::has_username() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RegisterServer_Return::set_has_username() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RegisterServer_Return::clear_has_username() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RegisterServer_Return::clear_username() {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& RegisterServer_Return::username() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Return.username)
  return *username_;
}
inline void RegisterServer_Return::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set:common.RegisterServer_Return.username)
}
inline void RegisterServer_Return::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set_char:common.RegisterServer_Return.username)
}
inline void RegisterServer_Return::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:common.RegisterServer_Return.username)
}
inline ::std::string* RegisterServer_Return::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:common.RegisterServer_Return.username)
  return username_;
}
inline ::std::string* RegisterServer_Return::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterServer_Return::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:common.RegisterServer_Return.username)
}

// optional int64 componentID = 5;
inline bool RegisterServer_Return::has_componentid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RegisterServer_Return::set_has_componentid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RegisterServer_Return::clear_has_componentid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RegisterServer_Return::clear_componentid() {
  componentid_ = GOOGLE_LONGLONG(0);
  clear_has_componentid();
}
inline ::google::protobuf::int64 RegisterServer_Return::componentid() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Return.componentID)
  return componentid_;
}
inline void RegisterServer_Return::set_componentid(::google::protobuf::int64 value) {
  set_has_componentid();
  componentid_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Return.componentID)
}

// optional int32 intaddr = 6;
inline bool RegisterServer_Return::has_intaddr() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RegisterServer_Return::set_has_intaddr() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RegisterServer_Return::clear_has_intaddr() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RegisterServer_Return::clear_intaddr() {
  intaddr_ = 0;
  clear_has_intaddr();
}
inline ::google::protobuf::int32 RegisterServer_Return::intaddr() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Return.intaddr)
  return intaddr_;
}
inline void RegisterServer_Return::set_intaddr(::google::protobuf::int32 value) {
  set_has_intaddr();
  intaddr_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Return.intaddr)
}

// optional int32 intport = 7;
inline bool RegisterServer_Return::has_intport() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RegisterServer_Return::set_has_intport() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RegisterServer_Return::clear_has_intport() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RegisterServer_Return::clear_intport() {
  intport_ = 0;
  clear_has_intport();
}
inline ::google::protobuf::int32 RegisterServer_Return::intport() const {
  // @@protoc_insertion_point(field_get:common.RegisterServer_Return.intport)
  return intport_;
}
inline void RegisterServer_Return::set_intport(::google::protobuf::int32 value) {
  set_has_intport();
  intport_ = value;
  // @@protoc_insertion_point(field_set:common.RegisterServer_Return.intport)
}

// -------------------------------------------------------------------

// ActiveTick

// optional int32 componentType = 1;
inline bool ActiveTick::has_componenttype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ActiveTick::set_has_componenttype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ActiveTick::clear_has_componenttype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ActiveTick::clear_componenttype() {
  componenttype_ = 0;
  clear_has_componenttype();
}
inline ::google::protobuf::int32 ActiveTick::componenttype() const {
  // @@protoc_insertion_point(field_get:common.ActiveTick.componentType)
  return componenttype_;
}
inline void ActiveTick::set_componenttype(::google::protobuf::int32 value) {
  set_has_componenttype();
  componenttype_ = value;
  // @@protoc_insertion_point(field_set:common.ActiveTick.componentType)
}

// optional int64 componentID = 2;
inline bool ActiveTick::has_componentid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ActiveTick::set_has_componentid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ActiveTick::clear_has_componentid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ActiveTick::clear_componentid() {
  componentid_ = GOOGLE_LONGLONG(0);
  clear_has_componentid();
}
inline ::google::protobuf::int64 ActiveTick::componentid() const {
  // @@protoc_insertion_point(field_get:common.ActiveTick.componentID)
  return componentid_;
}
inline void ActiveTick::set_componentid(::google::protobuf::int64 value) {
  set_has_componentid();
  componentid_ = value;
  // @@protoc_insertion_point(field_set:common.ActiveTick.componentID)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace common

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_common_2eproto__INCLUDED
