// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbmgrbase.proto

#ifndef PROTOBUF_dbmgrbase_2eproto__INCLUDED
#define PROTOBUF_dbmgrbase_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dbmgrbase {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dbmgrbase_2eproto();
void protobuf_AssignDesc_dbmgrbase_2eproto();
void protobuf_ShutdownFile_dbmgrbase_2eproto();

class DbmgrBroadcastInitCompleted;
class DbmgrBroadcastNewApp;

// ===================================================================

class DbmgrBroadcastInitCompleted : public ::google::protobuf::Message {
 public:
  DbmgrBroadcastInitCompleted();
  virtual ~DbmgrBroadcastInitCompleted();

  DbmgrBroadcastInitCompleted(const DbmgrBroadcastInitCompleted& from);

  inline DbmgrBroadcastInitCompleted& operator=(const DbmgrBroadcastInitCompleted& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DbmgrBroadcastInitCompleted& default_instance();

  void Swap(DbmgrBroadcastInitCompleted* other);

  // implements Message ----------------------------------------------

  DbmgrBroadcastInitCompleted* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DbmgrBroadcastInitCompleted& from);
  void MergeFrom(const DbmgrBroadcastInitCompleted& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 g_kbetime = 1;
  inline bool has_g_kbetime() const;
  inline void clear_g_kbetime();
  static const int kGKbetimeFieldNumber = 1;
  inline ::google::protobuf::uint32 g_kbetime() const;
  inline void set_g_kbetime(::google::protobuf::uint32 value);

  // optional int32 startEntityID = 2;
  inline bool has_startentityid() const;
  inline void clear_startentityid();
  static const int kStartEntityIDFieldNumber = 2;
  inline ::google::protobuf::int32 startentityid() const;
  inline void set_startentityid(::google::protobuf::int32 value);

  // optional int32 endEntityID = 3;
  inline bool has_endentityid() const;
  inline void clear_endentityid();
  static const int kEndEntityIDFieldNumber = 3;
  inline ::google::protobuf::int32 endentityid() const;
  inline void set_endentityid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dbmgrbase.DbmgrBroadcastInitCompleted)
 private:
  inline void set_has_g_kbetime();
  inline void clear_has_g_kbetime();
  inline void set_has_startentityid();
  inline void clear_has_startentityid();
  inline void set_has_endentityid();
  inline void clear_has_endentityid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 g_kbetime_;
  ::google::protobuf::int32 startentityid_;
  ::google::protobuf::int32 endentityid_;
  friend void  protobuf_AddDesc_dbmgrbase_2eproto();
  friend void protobuf_AssignDesc_dbmgrbase_2eproto();
  friend void protobuf_ShutdownFile_dbmgrbase_2eproto();

  void InitAsDefaultInstance();
  static DbmgrBroadcastInitCompleted* default_instance_;
};
// -------------------------------------------------------------------

class DbmgrBroadcastNewApp : public ::google::protobuf::Message {
 public:
  DbmgrBroadcastNewApp();
  virtual ~DbmgrBroadcastNewApp();

  DbmgrBroadcastNewApp(const DbmgrBroadcastNewApp& from);

  inline DbmgrBroadcastNewApp& operator=(const DbmgrBroadcastNewApp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DbmgrBroadcastNewApp& default_instance();

  void Swap(DbmgrBroadcastNewApp* other);

  // implements Message ----------------------------------------------

  DbmgrBroadcastNewApp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DbmgrBroadcastNewApp& from);
  void MergeFrom(const DbmgrBroadcastNewApp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 componentType = 1;
  inline bool has_componenttype() const;
  inline void clear_componenttype();
  static const int kComponentTypeFieldNumber = 1;
  inline ::google::protobuf::int32 componenttype() const;
  inline void set_componenttype(::google::protobuf::int32 value);

  // optional int32 uid = 2;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 2;
  inline ::google::protobuf::int32 uid() const;
  inline void set_uid(::google::protobuf::int32 value);

  // optional string username = 3;
  inline bool has_username() const;
  inline void clear_username();
  static const int kUsernameFieldNumber = 3;
  inline const ::std::string& username() const;
  inline void set_username(const ::std::string& value);
  inline void set_username(const char* value);
  inline void set_username(const char* value, size_t size);
  inline ::std::string* mutable_username();
  inline ::std::string* release_username();
  inline void set_allocated_username(::std::string* username);

  // optional int64 componentID = 4;
  inline bool has_componentid() const;
  inline void clear_componentid();
  static const int kComponentIDFieldNumber = 4;
  inline ::google::protobuf::int64 componentid() const;
  inline void set_componentid(::google::protobuf::int64 value);

  // optional int32 extaddr = 5;
  inline bool has_extaddr() const;
  inline void clear_extaddr();
  static const int kExtaddrFieldNumber = 5;
  inline ::google::protobuf::int32 extaddr() const;
  inline void set_extaddr(::google::protobuf::int32 value);

  // optional int32 extport = 6;
  inline bool has_extport() const;
  inline void clear_extport();
  static const int kExtportFieldNumber = 6;
  inline ::google::protobuf::int32 extport() const;
  inline void set_extport(::google::protobuf::int32 value);

  // optional int32 intaddr = 7;
  inline bool has_intaddr() const;
  inline void clear_intaddr();
  static const int kIntaddrFieldNumber = 7;
  inline ::google::protobuf::int32 intaddr() const;
  inline void set_intaddr(::google::protobuf::int32 value);

  // optional int32 intport = 8;
  inline bool has_intport() const;
  inline void clear_intport();
  static const int kIntportFieldNumber = 8;
  inline ::google::protobuf::int32 intport() const;
  inline void set_intport(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:dbmgrbase.DbmgrBroadcastNewApp)
 private:
  inline void set_has_componenttype();
  inline void clear_has_componenttype();
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_componentid();
  inline void clear_has_componentid();
  inline void set_has_extaddr();
  inline void clear_has_extaddr();
  inline void set_has_extport();
  inline void clear_has_extport();
  inline void set_has_intaddr();
  inline void clear_has_intaddr();
  inline void set_has_intport();
  inline void clear_has_intport();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 componenttype_;
  ::google::protobuf::int32 uid_;
  ::std::string* username_;
  ::google::protobuf::int64 componentid_;
  ::google::protobuf::int32 extaddr_;
  ::google::protobuf::int32 extport_;
  ::google::protobuf::int32 intaddr_;
  ::google::protobuf::int32 intport_;
  friend void  protobuf_AddDesc_dbmgrbase_2eproto();
  friend void protobuf_AssignDesc_dbmgrbase_2eproto();
  friend void protobuf_ShutdownFile_dbmgrbase_2eproto();

  void InitAsDefaultInstance();
  static DbmgrBroadcastNewApp* default_instance_;
};
// ===================================================================


// ===================================================================

// DbmgrBroadcastInitCompleted

// optional uint32 g_kbetime = 1;
inline bool DbmgrBroadcastInitCompleted::has_g_kbetime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DbmgrBroadcastInitCompleted::set_has_g_kbetime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DbmgrBroadcastInitCompleted::clear_has_g_kbetime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DbmgrBroadcastInitCompleted::clear_g_kbetime() {
  g_kbetime_ = 0u;
  clear_has_g_kbetime();
}
inline ::google::protobuf::uint32 DbmgrBroadcastInitCompleted::g_kbetime() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastInitCompleted.g_kbetime)
  return g_kbetime_;
}
inline void DbmgrBroadcastInitCompleted::set_g_kbetime(::google::protobuf::uint32 value) {
  set_has_g_kbetime();
  g_kbetime_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastInitCompleted.g_kbetime)
}

// optional int32 startEntityID = 2;
inline bool DbmgrBroadcastInitCompleted::has_startentityid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DbmgrBroadcastInitCompleted::set_has_startentityid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DbmgrBroadcastInitCompleted::clear_has_startentityid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DbmgrBroadcastInitCompleted::clear_startentityid() {
  startentityid_ = 0;
  clear_has_startentityid();
}
inline ::google::protobuf::int32 DbmgrBroadcastInitCompleted::startentityid() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastInitCompleted.startEntityID)
  return startentityid_;
}
inline void DbmgrBroadcastInitCompleted::set_startentityid(::google::protobuf::int32 value) {
  set_has_startentityid();
  startentityid_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastInitCompleted.startEntityID)
}

// optional int32 endEntityID = 3;
inline bool DbmgrBroadcastInitCompleted::has_endentityid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DbmgrBroadcastInitCompleted::set_has_endentityid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DbmgrBroadcastInitCompleted::clear_has_endentityid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DbmgrBroadcastInitCompleted::clear_endentityid() {
  endentityid_ = 0;
  clear_has_endentityid();
}
inline ::google::protobuf::int32 DbmgrBroadcastInitCompleted::endentityid() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastInitCompleted.endEntityID)
  return endentityid_;
}
inline void DbmgrBroadcastInitCompleted::set_endentityid(::google::protobuf::int32 value) {
  set_has_endentityid();
  endentityid_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastInitCompleted.endEntityID)
}

// -------------------------------------------------------------------

// DbmgrBroadcastNewApp

// optional int32 componentType = 1;
inline bool DbmgrBroadcastNewApp::has_componenttype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DbmgrBroadcastNewApp::set_has_componenttype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DbmgrBroadcastNewApp::clear_has_componenttype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DbmgrBroadcastNewApp::clear_componenttype() {
  componenttype_ = 0;
  clear_has_componenttype();
}
inline ::google::protobuf::int32 DbmgrBroadcastNewApp::componenttype() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastNewApp.componentType)
  return componenttype_;
}
inline void DbmgrBroadcastNewApp::set_componenttype(::google::protobuf::int32 value) {
  set_has_componenttype();
  componenttype_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastNewApp.componentType)
}

// optional int32 uid = 2;
inline bool DbmgrBroadcastNewApp::has_uid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DbmgrBroadcastNewApp::set_has_uid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DbmgrBroadcastNewApp::clear_has_uid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DbmgrBroadcastNewApp::clear_uid() {
  uid_ = 0;
  clear_has_uid();
}
inline ::google::protobuf::int32 DbmgrBroadcastNewApp::uid() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastNewApp.uid)
  return uid_;
}
inline void DbmgrBroadcastNewApp::set_uid(::google::protobuf::int32 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastNewApp.uid)
}

// optional string username = 3;
inline bool DbmgrBroadcastNewApp::has_username() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DbmgrBroadcastNewApp::set_has_username() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DbmgrBroadcastNewApp::clear_has_username() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DbmgrBroadcastNewApp::clear_username() {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_->clear();
  }
  clear_has_username();
}
inline const ::std::string& DbmgrBroadcastNewApp::username() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastNewApp.username)
  return *username_;
}
inline void DbmgrBroadcastNewApp::set_username(const ::std::string& value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastNewApp.username)
}
inline void DbmgrBroadcastNewApp::set_username(const char* value) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(value);
  // @@protoc_insertion_point(field_set_char:dbmgrbase.DbmgrBroadcastNewApp.username)
}
inline void DbmgrBroadcastNewApp::set_username(const char* value, size_t size) {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  username_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dbmgrbase.DbmgrBroadcastNewApp.username)
}
inline ::std::string* DbmgrBroadcastNewApp::mutable_username() {
  set_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    username_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:dbmgrbase.DbmgrBroadcastNewApp.username)
  return username_;
}
inline ::std::string* DbmgrBroadcastNewApp::release_username() {
  clear_has_username();
  if (username_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = username_;
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DbmgrBroadcastNewApp::set_allocated_username(::std::string* username) {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete username_;
  }
  if (username) {
    set_has_username();
    username_ = username;
  } else {
    clear_has_username();
    username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:dbmgrbase.DbmgrBroadcastNewApp.username)
}

// optional int64 componentID = 4;
inline bool DbmgrBroadcastNewApp::has_componentid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DbmgrBroadcastNewApp::set_has_componentid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DbmgrBroadcastNewApp::clear_has_componentid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DbmgrBroadcastNewApp::clear_componentid() {
  componentid_ = GOOGLE_LONGLONG(0);
  clear_has_componentid();
}
inline ::google::protobuf::int64 DbmgrBroadcastNewApp::componentid() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastNewApp.componentID)
  return componentid_;
}
inline void DbmgrBroadcastNewApp::set_componentid(::google::protobuf::int64 value) {
  set_has_componentid();
  componentid_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastNewApp.componentID)
}

// optional int32 extaddr = 5;
inline bool DbmgrBroadcastNewApp::has_extaddr() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DbmgrBroadcastNewApp::set_has_extaddr() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DbmgrBroadcastNewApp::clear_has_extaddr() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DbmgrBroadcastNewApp::clear_extaddr() {
  extaddr_ = 0;
  clear_has_extaddr();
}
inline ::google::protobuf::int32 DbmgrBroadcastNewApp::extaddr() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastNewApp.extaddr)
  return extaddr_;
}
inline void DbmgrBroadcastNewApp::set_extaddr(::google::protobuf::int32 value) {
  set_has_extaddr();
  extaddr_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastNewApp.extaddr)
}

// optional int32 extport = 6;
inline bool DbmgrBroadcastNewApp::has_extport() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void DbmgrBroadcastNewApp::set_has_extport() {
  _has_bits_[0] |= 0x00000020u;
}
inline void DbmgrBroadcastNewApp::clear_has_extport() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void DbmgrBroadcastNewApp::clear_extport() {
  extport_ = 0;
  clear_has_extport();
}
inline ::google::protobuf::int32 DbmgrBroadcastNewApp::extport() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastNewApp.extport)
  return extport_;
}
inline void DbmgrBroadcastNewApp::set_extport(::google::protobuf::int32 value) {
  set_has_extport();
  extport_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastNewApp.extport)
}

// optional int32 intaddr = 7;
inline bool DbmgrBroadcastNewApp::has_intaddr() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void DbmgrBroadcastNewApp::set_has_intaddr() {
  _has_bits_[0] |= 0x00000040u;
}
inline void DbmgrBroadcastNewApp::clear_has_intaddr() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void DbmgrBroadcastNewApp::clear_intaddr() {
  intaddr_ = 0;
  clear_has_intaddr();
}
inline ::google::protobuf::int32 DbmgrBroadcastNewApp::intaddr() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastNewApp.intaddr)
  return intaddr_;
}
inline void DbmgrBroadcastNewApp::set_intaddr(::google::protobuf::int32 value) {
  set_has_intaddr();
  intaddr_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastNewApp.intaddr)
}

// optional int32 intport = 8;
inline bool DbmgrBroadcastNewApp::has_intport() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void DbmgrBroadcastNewApp::set_has_intport() {
  _has_bits_[0] |= 0x00000080u;
}
inline void DbmgrBroadcastNewApp::clear_has_intport() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void DbmgrBroadcastNewApp::clear_intport() {
  intport_ = 0;
  clear_has_intport();
}
inline ::google::protobuf::int32 DbmgrBroadcastNewApp::intport() const {
  // @@protoc_insertion_point(field_get:dbmgrbase.DbmgrBroadcastNewApp.intport)
  return intport_;
}
inline void DbmgrBroadcastNewApp::set_intport(::google::protobuf::int32 value) {
  set_has_intport();
  intport_ = value;
  // @@protoc_insertion_point(field_set:dbmgrbase.DbmgrBroadcastNewApp.intport)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dbmgrbase

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dbmgrbase_2eproto__INCLUDED
