// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dbmgrbase.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dbmgrbase.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace dbmgrbase {

namespace {

const ::google::protobuf::Descriptor* DbmgrBroadcastInitCompleted_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DbmgrBroadcastInitCompleted_reflection_ = NULL;
const ::google::protobuf::Descriptor* DbmgrBroadcastNewApp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DbmgrBroadcastNewApp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_dbmgrbase_2eproto() {
  protobuf_AddDesc_dbmgrbase_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "dbmgrbase.proto");
  GOOGLE_CHECK(file != NULL);
  DbmgrBroadcastInitCompleted_descriptor_ = file->message_type(0);
  static const int DbmgrBroadcastInitCompleted_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastInitCompleted, g_kbetime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastInitCompleted, startentityid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastInitCompleted, endentityid_),
  };
  DbmgrBroadcastInitCompleted_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DbmgrBroadcastInitCompleted_descriptor_,
      DbmgrBroadcastInitCompleted::default_instance_,
      DbmgrBroadcastInitCompleted_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastInitCompleted, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastInitCompleted, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DbmgrBroadcastInitCompleted));
  DbmgrBroadcastNewApp_descriptor_ = file->message_type(1);
  static const int DbmgrBroadcastNewApp_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, componenttype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, uid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, componentid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, extaddr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, extport_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, intaddr_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, intport_),
  };
  DbmgrBroadcastNewApp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      DbmgrBroadcastNewApp_descriptor_,
      DbmgrBroadcastNewApp::default_instance_,
      DbmgrBroadcastNewApp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DbmgrBroadcastNewApp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(DbmgrBroadcastNewApp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_dbmgrbase_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DbmgrBroadcastInitCompleted_descriptor_, &DbmgrBroadcastInitCompleted::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    DbmgrBroadcastNewApp_descriptor_, &DbmgrBroadcastNewApp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_dbmgrbase_2eproto() {
  delete DbmgrBroadcastInitCompleted::default_instance_;
  delete DbmgrBroadcastInitCompleted_reflection_;
  delete DbmgrBroadcastNewApp::default_instance_;
  delete DbmgrBroadcastNewApp_reflection_;
}

void protobuf_AddDesc_dbmgrbase_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017dbmgrbase.proto\022\tdbmgrbase\"\\\n\033DbmgrBro"
    "adcastInitCompleted\022\021\n\tg_kbetime\030\001 \001(\r\022\025"
    "\n\rstartEntityID\030\002 \001(\005\022\023\n\013endEntityID\030\003 \001"
    "(\005\"\245\001\n\024DbmgrBroadcastNewApp\022\025\n\rcomponent"
    "Type\030\001 \001(\005\022\013\n\003uid\030\002 \001(\005\022\020\n\010username\030\003 \001("
    "\t\022\023\n\013componentID\030\004 \001(\003\022\017\n\007extaddr\030\005 \001(\005\022"
    "\017\n\007extport\030\006 \001(\005\022\017\n\007intaddr\030\007 \001(\005\022\017\n\007int"
    "port\030\010 \001(\005", 290);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dbmgrbase.proto", &protobuf_RegisterTypes);
  DbmgrBroadcastInitCompleted::default_instance_ = new DbmgrBroadcastInitCompleted();
  DbmgrBroadcastNewApp::default_instance_ = new DbmgrBroadcastNewApp();
  DbmgrBroadcastInitCompleted::default_instance_->InitAsDefaultInstance();
  DbmgrBroadcastNewApp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_dbmgrbase_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_dbmgrbase_2eproto {
  StaticDescriptorInitializer_dbmgrbase_2eproto() {
    protobuf_AddDesc_dbmgrbase_2eproto();
  }
} static_descriptor_initializer_dbmgrbase_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int DbmgrBroadcastInitCompleted::kGKbetimeFieldNumber;
const int DbmgrBroadcastInitCompleted::kStartEntityIDFieldNumber;
const int DbmgrBroadcastInitCompleted::kEndEntityIDFieldNumber;
#endif  // !_MSC_VER

DbmgrBroadcastInitCompleted::DbmgrBroadcastInitCompleted()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dbmgrbase.DbmgrBroadcastInitCompleted)
}

void DbmgrBroadcastInitCompleted::InitAsDefaultInstance() {
}

DbmgrBroadcastInitCompleted::DbmgrBroadcastInitCompleted(const DbmgrBroadcastInitCompleted& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dbmgrbase.DbmgrBroadcastInitCompleted)
}

void DbmgrBroadcastInitCompleted::SharedCtor() {
  _cached_size_ = 0;
  g_kbetime_ = 0u;
  startentityid_ = 0;
  endentityid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DbmgrBroadcastInitCompleted::~DbmgrBroadcastInitCompleted() {
  // @@protoc_insertion_point(destructor:dbmgrbase.DbmgrBroadcastInitCompleted)
  SharedDtor();
}

void DbmgrBroadcastInitCompleted::SharedDtor() {
  if (this != default_instance_) {
  }
}

void DbmgrBroadcastInitCompleted::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DbmgrBroadcastInitCompleted::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DbmgrBroadcastInitCompleted_descriptor_;
}

const DbmgrBroadcastInitCompleted& DbmgrBroadcastInitCompleted::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dbmgrbase_2eproto();
  return *default_instance_;
}

DbmgrBroadcastInitCompleted* DbmgrBroadcastInitCompleted::default_instance_ = NULL;

DbmgrBroadcastInitCompleted* DbmgrBroadcastInitCompleted::New() const {
  return new DbmgrBroadcastInitCompleted;
}

void DbmgrBroadcastInitCompleted::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<DbmgrBroadcastInitCompleted*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(g_kbetime_, endentityid_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DbmgrBroadcastInitCompleted::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dbmgrbase.DbmgrBroadcastInitCompleted)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 g_kbetime = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &g_kbetime_)));
          set_has_g_kbetime();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_startEntityID;
        break;
      }

      // optional int32 startEntityID = 2;
      case 2: {
        if (tag == 16) {
         parse_startEntityID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &startentityid_)));
          set_has_startentityid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_endEntityID;
        break;
      }

      // optional int32 endEntityID = 3;
      case 3: {
        if (tag == 24) {
         parse_endEntityID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &endentityid_)));
          set_has_endentityid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dbmgrbase.DbmgrBroadcastInitCompleted)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dbmgrbase.DbmgrBroadcastInitCompleted)
  return false;
#undef DO_
}

void DbmgrBroadcastInitCompleted::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dbmgrbase.DbmgrBroadcastInitCompleted)
  // optional uint32 g_kbetime = 1;
  if (has_g_kbetime()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->g_kbetime(), output);
  }

  // optional int32 startEntityID = 2;
  if (has_startentityid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->startentityid(), output);
  }

  // optional int32 endEntityID = 3;
  if (has_endentityid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->endentityid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dbmgrbase.DbmgrBroadcastInitCompleted)
}

::google::protobuf::uint8* DbmgrBroadcastInitCompleted::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dbmgrbase.DbmgrBroadcastInitCompleted)
  // optional uint32 g_kbetime = 1;
  if (has_g_kbetime()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->g_kbetime(), target);
  }

  // optional int32 startEntityID = 2;
  if (has_startentityid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->startentityid(), target);
  }

  // optional int32 endEntityID = 3;
  if (has_endentityid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->endentityid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dbmgrbase.DbmgrBroadcastInitCompleted)
  return target;
}

int DbmgrBroadcastInitCompleted::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 g_kbetime = 1;
    if (has_g_kbetime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->g_kbetime());
    }

    // optional int32 startEntityID = 2;
    if (has_startentityid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->startentityid());
    }

    // optional int32 endEntityID = 3;
    if (has_endentityid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->endentityid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DbmgrBroadcastInitCompleted::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DbmgrBroadcastInitCompleted* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DbmgrBroadcastInitCompleted*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DbmgrBroadcastInitCompleted::MergeFrom(const DbmgrBroadcastInitCompleted& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_g_kbetime()) {
      set_g_kbetime(from.g_kbetime());
    }
    if (from.has_startentityid()) {
      set_startentityid(from.startentityid());
    }
    if (from.has_endentityid()) {
      set_endentityid(from.endentityid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DbmgrBroadcastInitCompleted::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DbmgrBroadcastInitCompleted::CopyFrom(const DbmgrBroadcastInitCompleted& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DbmgrBroadcastInitCompleted::IsInitialized() const {

  return true;
}

void DbmgrBroadcastInitCompleted::Swap(DbmgrBroadcastInitCompleted* other) {
  if (other != this) {
    std::swap(g_kbetime_, other->g_kbetime_);
    std::swap(startentityid_, other->startentityid_);
    std::swap(endentityid_, other->endentityid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DbmgrBroadcastInitCompleted::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DbmgrBroadcastInitCompleted_descriptor_;
  metadata.reflection = DbmgrBroadcastInitCompleted_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int DbmgrBroadcastNewApp::kComponentTypeFieldNumber;
const int DbmgrBroadcastNewApp::kUidFieldNumber;
const int DbmgrBroadcastNewApp::kUsernameFieldNumber;
const int DbmgrBroadcastNewApp::kComponentIDFieldNumber;
const int DbmgrBroadcastNewApp::kExtaddrFieldNumber;
const int DbmgrBroadcastNewApp::kExtportFieldNumber;
const int DbmgrBroadcastNewApp::kIntaddrFieldNumber;
const int DbmgrBroadcastNewApp::kIntportFieldNumber;
#endif  // !_MSC_VER

DbmgrBroadcastNewApp::DbmgrBroadcastNewApp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:dbmgrbase.DbmgrBroadcastNewApp)
}

void DbmgrBroadcastNewApp::InitAsDefaultInstance() {
}

DbmgrBroadcastNewApp::DbmgrBroadcastNewApp(const DbmgrBroadcastNewApp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:dbmgrbase.DbmgrBroadcastNewApp)
}

void DbmgrBroadcastNewApp::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  componenttype_ = 0;
  uid_ = 0;
  username_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  componentid_ = GOOGLE_LONGLONG(0);
  extaddr_ = 0;
  extport_ = 0;
  intaddr_ = 0;
  intport_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

DbmgrBroadcastNewApp::~DbmgrBroadcastNewApp() {
  // @@protoc_insertion_point(destructor:dbmgrbase.DbmgrBroadcastNewApp)
  SharedDtor();
}

void DbmgrBroadcastNewApp::SharedDtor() {
  if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete username_;
  }
  if (this != default_instance_) {
  }
}

void DbmgrBroadcastNewApp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DbmgrBroadcastNewApp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DbmgrBroadcastNewApp_descriptor_;
}

const DbmgrBroadcastNewApp& DbmgrBroadcastNewApp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_dbmgrbase_2eproto();
  return *default_instance_;
}

DbmgrBroadcastNewApp* DbmgrBroadcastNewApp::default_instance_ = NULL;

DbmgrBroadcastNewApp* DbmgrBroadcastNewApp::New() const {
  return new DbmgrBroadcastNewApp;
}

void DbmgrBroadcastNewApp::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<DbmgrBroadcastNewApp*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(componenttype_, uid_);
    ZR_(componentid_, intport_);
    if (has_username()) {
      if (username_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        username_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool DbmgrBroadcastNewApp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dbmgrbase.DbmgrBroadcastNewApp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 componentType = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &componenttype_)));
          set_has_componenttype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_uid;
        break;
      }

      // optional int32 uid = 2;
      case 2: {
        if (tag == 16) {
         parse_uid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &uid_)));
          set_has_uid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_username;
        break;
      }

      // optional string username = 3;
      case 3: {
        if (tag == 26) {
         parse_username:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "username");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_componentID;
        break;
      }

      // optional int64 componentID = 4;
      case 4: {
        if (tag == 32) {
         parse_componentID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &componentid_)));
          set_has_componentid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_extaddr;
        break;
      }

      // optional int32 extaddr = 5;
      case 5: {
        if (tag == 40) {
         parse_extaddr:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &extaddr_)));
          set_has_extaddr();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_extport;
        break;
      }

      // optional int32 extport = 6;
      case 6: {
        if (tag == 48) {
         parse_extport:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &extport_)));
          set_has_extport();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_intaddr;
        break;
      }

      // optional int32 intaddr = 7;
      case 7: {
        if (tag == 56) {
         parse_intaddr:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intaddr_)));
          set_has_intaddr();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_intport;
        break;
      }

      // optional int32 intport = 8;
      case 8: {
        if (tag == 64) {
         parse_intport:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intport_)));
          set_has_intport();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dbmgrbase.DbmgrBroadcastNewApp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dbmgrbase.DbmgrBroadcastNewApp)
  return false;
#undef DO_
}

void DbmgrBroadcastNewApp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dbmgrbase.DbmgrBroadcastNewApp)
  // optional int32 componentType = 1;
  if (has_componenttype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->componenttype(), output);
  }

  // optional int32 uid = 2;
  if (has_uid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->uid(), output);
  }

  // optional string username = 3;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->username(), output);
  }

  // optional int64 componentID = 4;
  if (has_componentid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->componentid(), output);
  }

  // optional int32 extaddr = 5;
  if (has_extaddr()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->extaddr(), output);
  }

  // optional int32 extport = 6;
  if (has_extport()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->extport(), output);
  }

  // optional int32 intaddr = 7;
  if (has_intaddr()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->intaddr(), output);
  }

  // optional int32 intport = 8;
  if (has_intport()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->intport(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:dbmgrbase.DbmgrBroadcastNewApp)
}

::google::protobuf::uint8* DbmgrBroadcastNewApp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:dbmgrbase.DbmgrBroadcastNewApp)
  // optional int32 componentType = 1;
  if (has_componenttype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->componenttype(), target);
  }

  // optional int32 uid = 2;
  if (has_uid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->uid(), target);
  }

  // optional string username = 3;
  if (has_username()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "username");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->username(), target);
  }

  // optional int64 componentID = 4;
  if (has_componentid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->componentid(), target);
  }

  // optional int32 extaddr = 5;
  if (has_extaddr()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->extaddr(), target);
  }

  // optional int32 extport = 6;
  if (has_extport()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->extport(), target);
  }

  // optional int32 intaddr = 7;
  if (has_intaddr()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->intaddr(), target);
  }

  // optional int32 intport = 8;
  if (has_intport()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->intport(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dbmgrbase.DbmgrBroadcastNewApp)
  return target;
}

int DbmgrBroadcastNewApp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 componentType = 1;
    if (has_componenttype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->componenttype());
    }

    // optional int32 uid = 2;
    if (has_uid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->uid());
    }

    // optional string username = 3;
    if (has_username()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->username());
    }

    // optional int64 componentID = 4;
    if (has_componentid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->componentid());
    }

    // optional int32 extaddr = 5;
    if (has_extaddr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->extaddr());
    }

    // optional int32 extport = 6;
    if (has_extport()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->extport());
    }

    // optional int32 intaddr = 7;
    if (has_intaddr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->intaddr());
    }

    // optional int32 intport = 8;
    if (has_intport()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->intport());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DbmgrBroadcastNewApp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const DbmgrBroadcastNewApp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const DbmgrBroadcastNewApp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void DbmgrBroadcastNewApp::MergeFrom(const DbmgrBroadcastNewApp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_componenttype()) {
      set_componenttype(from.componenttype());
    }
    if (from.has_uid()) {
      set_uid(from.uid());
    }
    if (from.has_username()) {
      set_username(from.username());
    }
    if (from.has_componentid()) {
      set_componentid(from.componentid());
    }
    if (from.has_extaddr()) {
      set_extaddr(from.extaddr());
    }
    if (from.has_extport()) {
      set_extport(from.extport());
    }
    if (from.has_intaddr()) {
      set_intaddr(from.intaddr());
    }
    if (from.has_intport()) {
      set_intport(from.intport());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void DbmgrBroadcastNewApp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DbmgrBroadcastNewApp::CopyFrom(const DbmgrBroadcastNewApp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DbmgrBroadcastNewApp::IsInitialized() const {

  return true;
}

void DbmgrBroadcastNewApp::Swap(DbmgrBroadcastNewApp* other) {
  if (other != this) {
    std::swap(componenttype_, other->componenttype_);
    std::swap(uid_, other->uid_);
    std::swap(username_, other->username_);
    std::swap(componentid_, other->componentid_);
    std::swap(extaddr_, other->extaddr_);
    std::swap(extport_, other->extport_);
    std::swap(intaddr_, other->intaddr_);
    std::swap(intport_, other->intport_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata DbmgrBroadcastNewApp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DbmgrBroadcastNewApp_descriptor_;
  metadata.reflection = DbmgrBroadcastNewApp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dbmgrbase

// @@protoc_insertion_point(global_scope)
